-- Tabla de Categorías
CREATE TABLE categoria_documento (
    "ID_CATEGORIA_DOCUMENTO" SERIAL PRIMARY KEY,
    "STATUS" VARCHAR(20) NOT NULL,
    "NOMBRE" VARCHAR(100) NOT NULL,
    "DESCRIPCION" TEXT,
    "IMAGEN" VARCHAR(255),
    "SECUENCIA" INT,
    "DATE_CREATED" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Tabla de Documentos
CREATE TABLE documentos (
    "ID_DOCUMENTO" SERIAL PRIMARY KEY,
    "ID_CATEGORIA_DOCUMENTO" INT NOT NULL,
    "STATUS" VARCHAR(20) NOT NULL,
    "TITULO" VARCHAR(150) NOT NULL,
    "DESCRIPCION" TEXT,
    "ENLACE" VARCHAR(255),
    "SECUENCIA" INT,
    "DATE_CREATED" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    "TIPO_DOCUMENTO" VARCHAR(20),
    "MAS_BUSCADOS" BOOLEAN DEFAULT FALSE,
    "SECUENCIA_MAS_BUSCADA" INT,
    "DOCUMENTO_VER" VARCHAR(255),
    "INTERNO" BOOLEAN DEFAULT FALSE,
    "FECHA_ACTUALIZACION" TIMESTAMP,
    "FECHA_INICIO" TIMESTAMP,
    "FECHA_FIN" TIMESTAMP,
    "DOCUMENTO_DESCARGA" VARCHAR(255),
    "NOMBRE_DOCUMENTO" VARCHAR(150),
    "TYPE" VARCHAR(50),
    CONSTRAINT fk_categoria
        FOREIGN KEY ("ID_CATEGORIA_DOCUMENTO")
        REFERENCES categoria_documento("ID_CATEGORIA_DOCUMENTO")
        ON DELETE CASCADE
);
