--INSERTS PARA GRADO

INSERT INTO grado ("NUMERO_GRADO", "DESCRIPCION_GRADO", "NIVEL_EDUCATIVO") 
VALUES 
(1, '1° de Primaria', 'Primaria'),
(2, '2° de Primaria', 'Primaria'),
(3, '3° de Primaria', 'Primaria'),
(4, '4° de Primaria', 'Primaria'),
(5, '5° de Primaria', 'Primaria'),
(6, '6° de Primaria', 'Primaria'),
(7, '1° de Secundaria', 'Secundaria'),
(8, '2° de Secundaria', 'Secundaria'),
(9, '3° de Secundaria', 'Secundaria'),
(10, '4° de Secundaria', 'Secundaria'),
(11, '5° de Secundaria', 'Secundaria');




--INSERTS PARA PREGUNTAS

--PREGUNTAS IND. PARA PRIMER GRADO PRIMARIA
INSERT INTO pregunta (
    "TIPO_EVALUACION", "GRUPO", "TEXTO_TITULO", "TEXTO_SUPERIOR", "TEXTO_IMAGEN", 
    "TEXTO_INFERIOR", "ID_ARCHIVO_CARGA", "PREGUNTA", "OPCION_A", "OPCION_B", 
    "OPCION_C", "OPCION_D", "RESPUESTA_CORRECTA", "ID_COMPETENCIA", "POSTULA_ACTIVO", 
    "POSTULA_FECHA_CREACION", "POSTULA_USUARIO_CREACION", "POSTULA_HOST_CREACION", 
    "POSTULA_FECHA_ACTUALIZA", "POSTULA_USUARIO_ACTUALIZA", "POSTULA_HOST_ACTUALIZA", "ID_GRADO"
) 
VALUES
-- Pregunta 1
('Comunicación', NULL, 'El país de Francia', 'Francia es uno de los países más emblemáticos de Europa, conocido por su rica historia, cultura y arte. Además, su capital ha sido un centro político, cultural y turístico de gran relevancia a nivel mundial.', NULL, NULL, NULL, '¿Cuál es la capital de Francia?', 'Berlín', 'Madrid', 'Roma', 'París', 'D', 1, true, '2024-10-13 05:21:08', 'admin', 'localhost', '2024-10-13 05:21:08', 'admin', 'localhost', 1),
-- Pregunta 2
('Comunicación', NULL, 'El cuerpo humano', 'El corazón es un órgano vital que bombea sangre a través de todo el cuerpo. Se encuentra en el centro del pecho, ligeramente hacia la izquierda.', NULL, NULL, NULL, '¿Dónde se encuentra el corazón?', 'Cerca del estómago', 'En la cabeza', 'En el centro del pecho', 'En la pierna', 'C', 1, true, '2024-10-13 05:22:08', 'admin', 'localhost', '2024-10-13 05:22:08', 'admin', 'localhost', 1),
-- Pregunta 3
('Comunicación', NULL, 'La comida saludable', 'Una dieta balanceada es esencial para mantener una buena salud. Los alimentos como frutas, verduras y cereales integrales son muy beneficiosos.', NULL, NULL, NULL, '¿Cuál de estos es un alimento saludable?', 'Hamburguesa', 'Manzana', 'Papitas fritas', 'Galletas', 'B', 1, true, '2024-10-13 05:23:08', 'admin', 'localhost', '2024-10-13 05:23:08', 'admin', 'localhost', 1),
-- Pregunta 4
('Comunicación', NULL, 'El ciclo del agua', 'El ciclo del agua es el proceso mediante el cual el agua circula por la Tierra, pasando por distintos estados como líquido, vapor y sólido.', NULL, NULL, NULL, '¿Qué sucede cuando el agua se evapora?', 'Se convierte en hielo', 'Se convierte en gas', 'Se convierte en líquido', 'Se convierte en vapor', 'B', 1, true, '2024-10-13 05:24:08', 'admin', 'localhost', '2024-10-13 05:24:08', 'admin', 'localhost', 1),
-- Pregunta 5
('Comunicación', NULL, 'El sistema solar', 'El sistema solar está compuesto por el Sol, los planetas y otros cuerpos celestes. La Tierra es uno de los planetas que gira alrededor del Sol.', NULL, NULL, NULL, '¿Qué es el Sol?', 'Un planeta', 'Una estrella', 'Una luna', 'Un satélite', 'B', 1, true, '2024-10-13 05:25:08', 'admin', 'localhost', '2024-10-13 05:25:08', 'admin', 'localhost', 1),
-- Pregunta 6
('Comunicación', NULL, 'Las estaciones del año', 'Existen cuatro estaciones del año: primavera, verano, otoño e invierno, cada una con características propias como la temperatura y el clima.', NULL, NULL, NULL, '¿Cuál es la estación más cálida?', 'Primavera', 'Invierno', 'Otoño', 'Verano', 'D', 1, true, '2024-10-13 05:26:08', 'admin', 'localhost', '2024-10-13 05:26:08', 'admin', 'localhost', 1),
-- Pregunta 7
('Comunicación', NULL, 'La diversidad de animales', 'En la Tierra existen miles de especies de animales, algunos viven en el agua, otros en tierra y algunos en el aire. Cada uno tiene su hábitat natural.', NULL, NULL, NULL, '¿En qué vive un pez?', 'En el aire', 'En la tierra', 'En el agua', 'En la nieve', 'C', 1, true, '2024-10-13 05:27:08', 'admin', 'localhost', '2024-10-13 05:27:08', 'admin', 'localhost', 1),
-- Pregunta 8
('Comunicación', NULL, 'Los colores primarios', 'Los colores primarios son los tres colores básicos que no se pueden obtener mediante la mezcla de otros colores: rojo, azul y amarillo.', NULL, NULL, NULL, '¿Cuál de estos es un color primario?', 'Verde', 'Naranja', 'Amarillo', 'Marrón', 'C', 1, true, '2024-10-13 05:28:08', 'admin', 'localhost', '2024-10-13 05:28:08', 'admin', 'localhost', 1),
-- Pregunta 9
('Comunicación', NULL, 'El Día de la Independencia', 'El Día de la Independencia es una fecha muy importante para muchos países, ya que marca el momento en que se independizaron de otras naciones.', NULL, NULL, NULL, '¿Qué país celebra su independencia el 14 de julio?', 'México', 'Francia', 'Estados Unidos', 'España', 'B', 1, true, '2024-10-13 05:29:08', 'admin', 'localhost', '2024-10-13 05:29:08', 'admin', 'localhost', 1),
-- Pregunta 10
('Comunicación', NULL, 'La naturaleza', 'La naturaleza nos proporciona recursos que son fundamentales para nuestra supervivencia, como el agua, el aire y la tierra.', NULL, NULL, NULL, '¿Qué recurso es vital para la vida humana?', 'Plástico', 'Aire', 'Petróleo', 'Cobre', 'B', 1, true, '2024-10-13 05:30:08', 'admin', 'localhost', '2024-10-13 05:30:08', 'admin', 'localhost', 1),
-- Pregunta 11
('Comunicación', NULL, 'Las formas geométricas', 'Existen muchas formas geométricas, como círculos, cuadrados y triángulos, que podemos observar en el mundo que nos rodea.', NULL, NULL, NULL, '¿Cuál es la forma de una pelota?', 'Cuadrada', 'Rectangular', 'Triangular', 'Esférica', 'D', 1, true, '2024-10-13 05:31:08', 'admin', 'localhost', '2024-10-13 05:31:08', 'admin', 'localhost', 1),
-- Pregunta 12
('Comunicación', NULL, 'El reciclaje', 'Reciclar es un proceso en el que los materiales usados se convierten en nuevos productos. Esto ayuda a reducir el impacto ambiental.', NULL, NULL, NULL, '¿Qué tipo de material se puede reciclar?', 'Vidrio', 'Comida', 'Hielo', 'Agua', 'A', 1, true, '2024-10-13 05:32:08', 'admin', 'localhost', '2024-10-13 05:32:08', 'admin', 'localhost', 1),
-- Pregunta 13
('Comunicación', NULL, 'Los animales domésticos', 'Los animales domésticos son aquellos que vivimos cerca de nosotros, como perros y gatos. Estos animales nos brindan compañía y nos enseñan sobre el cuidado.', NULL, NULL, NULL, '¿Cuál es un animal doméstico?', 'León', 'Tigre', 'Perro', 'Cebra', 'C', 1, true, '2024-10-13 05:33:08', 'admin', 'localhost', '2024-10-13 05:33:08', 'admin', 'localhost', 1),
-- Pregunta 14
('Comunicación', NULL, 'Las partes de una planta', 'Las plantas tienen diferentes partes que les permiten crecer y desarrollarse, como las raíces, el tallo y las hojas.', NULL, NULL, NULL, '¿Qué parte de la planta se encuentra bajo tierra?', 'Raíz', 'Hoja', 'Flor', 'Fruto', 'A', 1, true, '2024-10-13 05:34:08', 'admin', 'localhost', '2024-10-13 05:34:08', 'admin', 'localhost', 1),
-- Pregunta 15
('Comunicación', NULL, 'Los continentes', 'El planeta Tierra está dividido en varios continentes, cada uno con su propio clima, cultura y geografía.', NULL, NULL, NULL, '¿En qué continente se encuentra Brasil?', 'Asia', 'América', 'Europa', 'África', 'B', 1, true, '2024-10-13 05:35:08', 'admin', 'localhost', '2024-10-13 05:35:08', 'admin', 'localhost', 1),
-- Pregunta 16
('Comunicación', NULL, 'El transporte', 'El transporte es vital para movilizarse de un lugar a otro. Existen diferentes tipos de transporte como el terrestre, aéreo y acuático.', NULL, NULL, NULL, '¿Qué tipo de transporte utilizas para volar?', 'Bicicleta', 'Avión', 'Coche', 'Barco', 'B', 1, true, '2024-10-13 05:36:08', 'admin', 'localhost', '2024-10-13 05:36:08', 'admin', 'localhost', 1),
-- Pregunta 17
('Comunicación', NULL, 'Los medios de comunicación', 'Los medios de comunicación son herramientas importantes que permiten compartir información con muchas personas, como la televisión, la radio y la internet.', NULL, NULL, NULL, '¿Qué medio de comunicación utilizas para ver películas?', 'Internet', 'Teléfono', 'Televisión', 'Correo', 'C', 1, true, '2024-10-13 05:37:08', 'admin', 'localhost', '2024-10-13 05:37:08', 'admin', 'localhost', 1),
-- Pregunta 18
('Comunicación', NULL, 'El clima', 'El clima varía en diferentes partes del mundo. Algunos lugares son fríos, mientras que otros son cálidos o templados.', NULL, NULL, NULL, '¿En qué tipo de clima viven los pingüinos?', 'Cálido', 'Tropical', 'Frío', 'Templado', 'C', 1, true, '2024-10-13 05:38:08', 'admin', 'localhost', '2024-10-13 05:38:08', 'admin', 'localhost', 1),
-- Pregunta 19
('Comunicación', NULL, 'Las plantas y sus beneficios', 'Las plantas son fundamentales para la vida en la Tierra, ya que producen oxígeno, alimento y sombra.', NULL, NULL, NULL, '¿Qué producen las plantas que es vital para los seres humanos?', 'Comida', 'Oxígeno', 'Luz', 'Agua', 'B', 1, true, '2024-10-13 05:39:08', 'admin', 'localhost', '2024-10-13 05:39:08', 'admin', 'localhost', 1),
-- Pregunta 20
('Comunicación', NULL, 'El respeto', 'El respeto es una de las bases de la convivencia humana. Respetar a los demás nos ayuda a vivir en armonía.', NULL, NULL, NULL, '¿Qué es el respeto?', 'Molestar a los demás', 'Escuchar y entender a los demás', 'Ser egoísta', 'Hablar mucho', 'B', 1, true, '2024-10-13 05:40:08', 'admin', 'localhost', '2024-10-13 05:40:08', 'admin', 'localhost', 1);


--PREGUNTAS IND. PARA SEGUNDO GRADO PRIMARIA
INSERT INTO pregunta (
    "TIPO_EVALUACION", "GRUPO", "TEXTO_TITULO", "TEXTO_SUPERIOR", "TEXTO_IMAGEN", "TEXTO_INFERIOR", 
    "ID_ARCHIVO_CARGA", "PREGUNTA", "OPCION_A", "OPCION_B", "OPCION_C", "OPCION_D", "RESPUESTA_CORRECTA", 
    "ID_COMPETENCIA", "POSTULA_ACTIVO", "POSTULA_FECHA_CREACION", "POSTULA_USUARIO_CREACION", "POSTULA_HOST_CREACION", 
    "POSTULA_FECHA_ACTUALIZA", "POSTULA_USUARIO_ACTUALIZA", "POSTULA_HOST_ACTUALIZA", "ID_GRADO"
) VALUES
-- Pregunta 1
('Matemática', NULL, 'Suma', NULL, NULL, NULL, NULL, '¿Cuánto es 5 + 7?', '10', '11', '12', '13', 'B', 1, true, '2024-10-13 05:21:08', 'admin', 'localhost', '2024-10-13 05:21:08', 'admin', 'localhost', 2),
-- Pregunta 2
('Matemática', NULL, 'Resta', NULL, NULL, NULL, NULL, '¿Cuánto es 9 - 4?', '5', '6', '7', '8', 'A', 1, true, '2024-10-13 05:21:08', 'admin', 'localhost', '2024-10-13 05:21:08', 'admin', 'localhost', 2),
-- Pregunta 3
('Matemática', NULL, 'Multiplicación', NULL, NULL, NULL, NULL, '¿Cuánto es 6 × 3?', '15', '18', '21', '24', 'B', 1, true, '2024-10-13 05:21:08', 'admin', 'localhost', '2024-10-13 05:21:08', 'admin', 'localhost', 2),
-- Pregunta 4
('Matemática', NULL, 'División', NULL, NULL, NULL, NULL, '¿Cuánto es 8 ÷ 2?', '3', '4', '5', '6', 'B', 1, true, '2024-10-13 05:21:08', 'admin', 'localhost', '2024-10-13 05:21:08', 'admin', 'localhost', 2),
-- Pregunta 5
('Matemática', NULL, 'Sumas con decimales', NULL, NULL, NULL, NULL, '¿Cuánto es 0.5 + 0.5?', '1', '1.5', '2', '2.5', 'A', 1, true, '2024-10-13 05:21:08', 'admin', 'localhost', '2024-10-13 05:21:08', 'admin', 'localhost', 2),
-- Pregunta 6
('Matemática', NULL, 'Resta de decimales', NULL, NULL, NULL, NULL, '¿Cuánto es 3.5 - 1.5?', '1.5', '2', '2.5', '3', 'A', 1, true, '2024-10-13 05:21:08', 'admin', 'localhost', '2024-10-13 05:21:08', 'admin', 'localhost', 2),
-- Pregunta 7
('Matemática', NULL, 'Multiplicación con decimales', NULL, NULL, NULL, NULL, '¿Cuánto es 0.5 × 4?', '1', '1.5', '2', '2.5', 'A', 1, true, '2024-10-13 05:21:08', 'admin', 'localhost', '2024-10-13 05:21:08', 'admin', 'localhost', 2),
-- Pregunta 8
('Matemática', NULL, 'División con decimales', NULL, NULL, NULL, NULL, '¿Cuánto es 6 ÷ 2.0?', '2', '3', '3.5', '4', 'B', 1, true, '2024-10-13 05:21:08', 'admin', 'localhost', '2024-10-13 05:21:08', 'admin', 'localhost', 2),
-- Pregunta 9
('Matemática', NULL, 'Suma de fracciones', NULL, NULL, NULL, NULL, '¿Cuánto es 1/2 + 1/4?', '3/4', '1', '1/2', '2/4', 'A', 1, true, '2024-10-13 05:21:08', 'admin', 'localhost', '2024-10-13 05:21:08', 'admin', 'localhost', 2),
-- Pregunta 10
('Matemática', NULL, 'Resta de fracciones', NULL, NULL, NULL, NULL, '¿Cuánto es 3/4 - 1/4?', '1/2', '1/4', '2/4', '3/4', 'A', 1, true, '2024-10-13 05:21:08', 'admin', 'localhost', '2024-10-13 05:21:08', 'admin', 'localhost', 2),
-- Pregunta 11
('Matemática', NULL, 'Suma de números grandes', NULL, NULL, NULL, NULL, '¿Cuánto es 456 + 789?', '1245', '1234', '1233', '1345', 'A', 1, true, '2024-10-13 05:21:08', 'admin', 'localhost', '2024-10-13 05:21:08', 'admin', 'localhost', 2),
-- Pregunta 12
('Matemática', NULL, 'Resta de números grandes', NULL, NULL, NULL, NULL, '¿Cuánto es 900 - 456?', '444', '450', '460', '470', 'A', 1, true, '2024-10-13 05:21:08', 'admin', 'localhost', '2024-10-13 05:21:08', 'admin', 'localhost', 2),
-- Pregunta 13
('Matemática', NULL, 'Comparación de números', NULL, NULL, NULL, NULL, '¿Cuál es el mayor número entre 45 y 54?', '45', '50', '54', '55', 'C', 1, true, '2024-10-13 05:21:08', 'admin', 'localhost', '2024-10-13 05:21:08', 'admin', 'localhost', 2),
-- Pregunta 14
('Matemática', NULL, 'Suma con decimales y fracciones', NULL, NULL, NULL, NULL, '¿Cuánto es 1/2 + 0.5?', '1', '1.5', '2', '2.5', 'A', 1, true, '2024-10-13 05:21:08', 'admin', 'localhost', '2024-10-13 05:21:08', 'admin', 'localhost', 2),
-- Pregunta 15
('Matemática', NULL, 'Multiplicación de números grandes', NULL, NULL, NULL, NULL, '¿Cuánto es 12 × 15?', '150', '160', '170', '180', 'A', 1, true, '2024-10-13 05:21:08', 'admin', 'localhost', '2024-10-13 05:21:08', 'admin', 'localhost', 2),
-- Pregunta 16
('Matemática', NULL, 'División con residuos', NULL, NULL, NULL, NULL, '¿Cuánto es 15 ÷ 4?', '3', '3.5', '4', '4.5', 'A', 1, true, '2024-10-13 05:21:08', 'admin', 'localhost', '2024-10-13 05:21:08', 'admin', 'localhost', 2),
-- Pregunta 17
('Matemática', NULL, 'Operaciones combinadas', NULL, NULL, NULL, NULL, '¿Cuánto es 5 + 3 × 2?', '11', '16', '14', '10', 'A', 1, true, '2024-10-13 05:21:08', 'admin', 'localhost', '2024-10-13 05:21:08', 'admin', 'localhost', 2),
-- Pregunta 18
('Matemática', NULL, 'Problema de palabras', NULL, NULL, NULL, NULL, 'Si tienes 5 manzanas y compras 3 más, ¿cuántas manzanas tienes?', '6', '7', '8', '9', 'B', 1, true, '2024-10-13 05:21:08', 'admin', 'localhost', '2024-10-13 05:21:08', 'admin', 'localhost', 2),
-- Pregunta 19
('Matemática', NULL, 'Conteo', NULL, NULL, NULL, NULL, '¿Cuántos números hay entre 5 y 10?', '3', '4', '5', '6', 'B', 1, true, '2024-10-13 05:21:08', 'admin', 'localhost', '2024-10-13 05:21:08', 'admin', 'localhost', 2),
-- Pregunta 20
('Matemática', NULL, 'Suma de decimales', NULL, NULL, NULL, NULL, '¿Cuánto es 0.75 + 0.25?', '1', '1.5', '0.5', '2', 'A', 1, true, '2024-10-13 05:21:08', 'admin', 'localhost', '2024-10-13 05:21:08', 'admin', 'localhost', 2);


--PREGUNTAS IND. PARA TERCER GRADO PRIMARIA

INSERT INTO pregunta ("TIPO_EVALUACION", "GRUPO", "TEXTO_TITULO", "TEXTO_SUPERIOR", "TEXTO_IMAGEN", "TEXTO_INFERIOR", "ID_ARCHIVO_CARGA", "PREGUNTA", "OPCION_A", "OPCION_B", "OPCION_C", "OPCION_D", "RESPUESTA_CORRECTA", "ID_COMPETENCIA", "POSTULA_ACTIVO", "POSTULA_FECHA_CREACION", "POSTULA_USUARIO_CREACION", "POSTULA_HOST_CREACION", "POSTULA_FECHA_ACTUALIZA", "POSTULA_USUARIO_ACTUALIZA", "POSTULA_HOST_ACTUALIZA", "ID_GRADO")
VALUES
('Ciencia y Ambiente', NULL, 'El país de Francia', 'Francia es uno de los países más emblemáticos de Europa, conocido por su rica historia, cultura y arte. Además, su capital ha sido un centro político, cultural y turístico de gran relevancia a nivel mundial.', NULL, NULL, NULL, '¿Cuál es la capital de Francia?', 'Berlín', 'Madrid', 'Roma', 'París', 'D', 1, true, '2024-10-13 05:21:08.597681', 'admin', 'localhost', '2024-10-13 05:21:08.597681', 'admin', 'localhost', 3),
('Ciencia y Ambiente', NULL, 'El sistema solar', 'El sistema solar está compuesto por el sol, los planetas y otros cuerpos celestes. Los planetas giran alrededor del sol en órbitas específicas.', NULL, NULL, NULL, '¿Cuál es el planeta más cercano al sol?', 'Venus', 'Mercurio', 'Marte', 'Júpiter', 'B', 1, true, '2024-10-13 05:21:08.597681', 'admin', 'localhost', '2024-10-13 05:21:08.597681', 'admin', 'localhost', 3),
('Ciencia y Ambiente', NULL, 'El ciclo del agua', 'El ciclo del agua describe cómo el agua se mueve a través de la atmósfera, la superficie terrestre y el subsuelo. Incluye procesos como la evaporación y la precipitación.', NULL, NULL, NULL, '¿Qué proceso en el ciclo del agua convierte el agua de un líquido a vapor?', 'Evaporación', 'Condensación', 'Precipitación', 'Filtración', 'A', 1, true, '2024-10-13 05:21:08.597681', 'admin', 'localhost', '2024-10-13 05:21:08.597681', 'admin', 'localhost', 3),
('Ciencia y Ambiente', NULL, 'Los ecosistemas', 'Un ecosistema es una comunidad de seres vivos que interactúan entre sí y con su entorno físico. Esto incluye factores como la temperatura, la luz y el agua.', NULL, NULL, NULL, '¿Qué tipo de ecosistema se encuentra en el desierto?', 'Bosque tropical', 'Pradera', 'Desierto', 'Marino', 'C', 1, true, '2024-10-13 05:21:08.597681', 'admin', 'localhost', '2024-10-13 05:21:08.597681', 'admin', 'localhost', 3),
('Ciencia y Ambiente', NULL, 'La fotosíntesis', 'La fotosíntesis es el proceso por el cual las plantas producen su propio alimento usando la luz solar, dióxido de carbono y agua.', NULL, NULL, NULL, '¿Qué gas las plantas absorben para realizar la fotosíntesis?', 'Oxígeno', 'Nitrógeno', 'Dióxido de carbono', 'Metano', 'C', 1, true, '2024-10-13 05:21:08.597681', 'admin', 'localhost', '2024-10-13 05:21:08.597681', 'admin', 'localhost', 3),
('Ciencia y Ambiente', NULL, 'El agua en la naturaleza', 'El agua cubre más del 70% de la superficie terrestre. Es esencial para la vida y se encuentra en tres estados: sólido, líquido y gaseoso.', NULL, NULL, NULL, '¿En qué estado del agua encontramos el hielo?', 'Líquido', 'Gas', 'Sólido', 'Plasma', 'C', 1, true, '2024-10-13 05:21:08.597681', 'admin', 'localhost', '2024-10-13 05:21:08.597681', 'admin', 'localhost', 3),
('Ciencia y Ambiente', NULL, 'La cadena alimentaria', 'La cadena alimentaria describe cómo la energía fluye a través de un ecosistema, comenzando con las plantas y pasando a los animales que las consumen.', NULL, NULL, NULL, '¿Qué tipo de organismo es el primero en la cadena alimentaria?', 'Herbívoro', 'Carnívoro', 'Productor', 'Descomponedor', 'C', 1, true, '2024-10-13 05:21:08.597681', 'admin', 'localhost', '2024-10-13 05:21:08.597681', 'admin', 'localhost', 3),
('Ciencia y Ambiente', NULL, 'El clima', 'El clima de una región se refiere al patrón de condiciones atmosféricas que ocurren a largo plazo, como la temperatura y la precipitación.', NULL, NULL, NULL, '¿Cómo se llama el estudio del clima?', 'Meteorología', 'Climatología', 'Geografía', 'Física', 'B', 1, true, '2024-10-13 05:21:08.597681', 'admin', 'localhost', '2024-10-13 05:21:08.597681', 'admin', 'localhost', 3),
('Ciencia y Ambiente', NULL, 'Las estaciones del año', 'Las estaciones del año son períodos de tiempo que tienen características climáticas distintas. Son cuatro: primavera, verano, otoño e invierno.', NULL, NULL, NULL, '¿En qué estación del año las hojas de los árboles caen?', 'Primavera', 'Verano', 'Otoño', 'Invierno', 'C', 1, true, '2024-10-13 05:21:08.597681', 'admin', 'localhost', '2024-10-13 05:21:08.597681', 'admin', 'localhost', 3),
('Ciencia y Ambiente', NULL, 'La energía', 'La energía es la capacidad de realizar trabajo. Puede encontrarse en varias formas como energía solar, eólica, térmica y cinética.', NULL, NULL, NULL, '¿Qué tipo de energía proviene del sol?', 'Energía térmica', 'Energía eólica', 'Energía solar', 'Energía nuclear', 'C', 1, true, '2024-10-13 05:21:08.597681', 'admin', 'localhost', '2024-10-13 05:21:08.597681', 'admin', 'localhost', 3),
('Ciencia y Ambiente', NULL, 'La materia', 'La materia es todo lo que tiene masa y ocupa espacio. Está compuesta por átomos y se presenta en tres estados: sólido, líquido y gaseoso.', NULL, NULL, NULL, '¿Cuál es el estado de la materia que ocupa más espacio?', 'Sólido', 'Líquido', 'Gaseoso', 'Plasma', 'C', 1, true, '2024-10-13 05:21:08.597681', 'admin', 'localhost', '2024-10-13 05:21:08.597681', 'admin', 'localhost', 3),
('Ciencia y Ambiente', NULL, 'Los animales', 'Los animales son seres vivos que se caracterizan por su capacidad de moverse, alimentarse y reproducirse. Están clasificados en vertebrados e invertebrados.', NULL, NULL, NULL, '¿Qué tipo de animales son los mamíferos?', 'Vertebrados', 'Invertebrados', 'Ambos', 'Ninguno', 'A', 1, true, '2024-10-13 05:21:08.597681', 'admin', 'localhost', '2024-10-13 05:21:08.597681', 'admin', 'localhost', 3),
('Ciencia y Ambiente', NULL, 'El aire', 'El aire es una mezcla de gases que rodea la Tierra. Es esencial para la vida, ya que los seres vivos lo respiran.', NULL, NULL, NULL, '¿Qué gas es el más abundante en el aire?', 'Oxígeno', 'Dióxido de carbono', 'Nitrógeno', 'Helio', 'C', 1, true, '2024-10-13 05:21:08.597681', 'admin', 'localhost', '2024-10-13 05:21:08.597681', 'admin', 'localhost', 3),
('Ciencia y Ambiente', NULL, 'Las plantas', 'Las plantas son organismos que realizan la fotosíntesis, produciendo oxígeno y alimento. Son esenciales para el equilibrio de los ecosistemas.', NULL, NULL, NULL, '¿Qué parte de la planta absorbe agua y nutrientes del suelo?', 'Raíz', 'Tallo', 'Hoja', 'Flor', 'A', 1, true, '2024-10-13 05:21:08.597681', 'admin', 'localhost', '2024-10-13 05:21:08.597681', 'admin', 'localhost', 3),
('Ciencia y Ambiente', NULL, 'El reciclaje', 'El reciclaje es el proceso de convertir los materiales desechados en nuevos productos, ayudando a reducir el consumo de recursos naturales.', NULL, NULL, NULL, '¿Qué material se puede reciclar fácilmente?', 'Vidrio', 'Papel', 'Plástico', 'Aluminio', 'A', 1, true, '2024-10-13 05:21:08.597681', 'admin', 'localhost', '2024-10-13 05:21:08.597681', 'admin', 'localhost', 3),
('Ciencia y Ambiente', NULL, 'El cuerpo humano', 'El cuerpo humano está compuesto por varios sistemas que trabajan en conjunto para permitir el funcionamiento adecuado del organismo.', NULL, NULL, NULL, '¿Qué sistema del cuerpo humano transporta la sangre?', 'Sistema digestivo', 'Sistema circulatorio', 'Sistema respiratorio', 'Sistema nervioso', 'B', 1, true, '2024-10-13 05:21:08.597681', 'admin', 'localhost', '2024-10-13 05:21:08.597681', 'admin', 'localhost', 3),
('Ciencia y Ambiente', NULL, 'El sol', 'El sol es una estrella que proporciona luz y calor a la Tierra. Es fundamental para la vida en nuestro planeta.', NULL, NULL, NULL, '¿Qué tipo de energía produce el sol?', 'Energía eléctrica', 'Energía térmica', 'Energía química', 'Energía solar', 'D', 1, true, '2024-10-13 05:21:08.597681', 'admin', 'localhost', '2024-10-13 05:21:08.597681', 'admin', 'localhost', 3),
('Ciencia y Ambiente', NULL, 'Los seres vivos', 'Todos los seres vivos tienen características comunes como la capacidad de crecer, reproducirse y reaccionar a estímulos.', NULL, NULL, NULL, '¿Qué característica es común en todos los seres vivos?', 'Nacer', 'Reproducirse', 'Respirar', 'Crecer', 'B', 1, true, '2024-10-13 05:21:08.597681', 'admin', 'localhost', '2024-10-13 05:21:08.597681', 'admin', 'localhost', 3),
('Ciencia y Ambiente', NULL, 'Los seres vivos', 'Todos los seres vivos tienen características comunes como la capacidad de crecer, reproducirse y reaccionar a estímulos.', NULL, NULL, NULL, '¿Qué característica es común en todos los seres vivos?', 'Nacer', 'Reproducirse', 'Respirar', 'Crecer', 'B', 1, true, '2024-10-13 05:21:08.597681', 'admin', 'localhost', '2024-10-13 05:21:08.597681', 'admin', 'localhost', 3),
('Ciencia y Ambiente', NULL, 'La fotosíntesis', 'La fotosíntesis es el proceso mediante el cual las plantas producen su propio alimento utilizando luz, agua y dióxido de carbono.', NULL, NULL, NULL, '¿Qué recurso es necesario para que las plantas realicen la fotosíntesis?', 'Luz', 'Viento', 'Agua', 'Tierra', 'A', 1, true, '2024-10-13 05:21:08.597681', 'admin', 'localhost', '2024-10-13 05:21:08.597681', 'admin', 'localhost', 3);



--PREGUNTAS IND. PARA CUARTO GRADO PRIMARIA

INSERT INTO pregunta (
    "TIPO_EVALUACION", "GRUPO", "TEXTO_TITULO", "TEXTO_SUPERIOR", 
    "TEXTO_IMAGEN", "TEXTO_INFERIOR", "ID_ARCHIVO_CARGA", "PREGUNTA", 
    "OPCION_A", "OPCION_B", "OPCION_C", "OPCION_D", "RESPUESTA_CORRECTA", 
    "ID_COMPETENCIA", "POSTULA_ACTIVO", "POSTULA_FECHA_CREACION", 
    "POSTULA_USUARIO_CREACION", "POSTULA_HOST_CREACION", "POSTULA_FECHA_ACTUALIZA", 
    "POSTULA_USUARIO_ACTUALIZA", "POSTULA_HOST_ACTUALIZA", "ID_GRADO"
) 
VALUES
-- Pregunta 1
('Ciencias Sociales', NULL, 'Los seres vivos', 'Todos los seres vivos tienen características comunes como la capacidad de crecer, reproducirse y reaccionar a estímulos.', NULL, NULL, NULL, '¿Qué característica es común en todos los seres vivos?', 'Nacer', 'Reproducirse', 'Respirar', 'Crecer', 'B', 1, true, '2024-10-13 05:21:08.597681', 'admin', 'localhost', '2024-10-13 05:21:08.597681', 'admin', 'localhost', 4),

-- Pregunta 2
('Ciencias Sociales', NULL, 'Las estaciones del año', 'Las estaciones del año son ciclos que dependen de la inclinación de la Tierra. Existen cuatro estaciones: primavera, verano, otoño e invierno.', NULL, NULL, NULL, '¿Cuántas estaciones del año existen?', 'Tres', 'Cuatro', 'Cinco', 'Seis', 'B', 1, true, '2024-10-13 05:22:08.597681', 'admin', 'localhost', '2024-10-13 05:22:08.597681', 'admin', 'localhost', 4),

-- Pregunta 3
('Ciencias Sociales', NULL, 'Los continentes', 'La Tierra está dividida en continentes que son grandes masas de tierra. El número de continentes en el planeta es siete.', NULL, NULL, NULL, '¿Cuántos continentes hay en la Tierra?', 'Cinco', 'Seis', 'Siete', 'Ocho', 'C', 1, true, '2024-10-13 05:23:08.597681', 'admin', 'localhost', '2024-10-13 05:23:08.597681', 'admin', 'localhost', 4),

-- Pregunta 4
('Ciencias Sociales', NULL, 'Los océanos', 'Los océanos son grandes cuerpos de agua salada que cubren la mayor parte de la superficie de la Tierra.', NULL, NULL, NULL, '¿Qué cubre la mayor parte de la superficie de la Tierra?', 'Desiertos', 'Bosques', 'Océanos', 'Montañas', 'C', 1, true, '2024-10-13 05:24:08.597681', 'admin', 'localhost', '2024-10-13 05:24:08.597681', 'admin', 'localhost', 4),

-- Pregunta 5
('Ciencias Sociales', NULL, 'La población mundial', 'La población mundial es el número total de personas que viven en el planeta. Este número aumenta cada año debido a la natalidad.', NULL, NULL, NULL, '¿Qué factor influye en el aumento de la población mundial?', 'Mortalidad', 'Emigración', 'Natalidad', 'Inmigración', 'C', 1, true, '2024-10-13 05:25:08.597681', 'admin', 'localhost', '2024-10-13 05:25:08.597681', 'admin', 'localhost', 4),

-- Pregunta 6
('Ciencias Sociales', NULL, 'El clima', 'El clima de una región depende de varios factores como la latitud, la altitud y la proximidad al mar.', NULL, NULL, NULL, '¿Qué factor influye en el clima de una región?', 'Latitud', 'Peso', 'Edad', 'Color', 'A', 1, true, '2024-10-13 05:26:08.597681', 'admin', 'localhost', '2024-10-13 05:26:08.597681', 'admin', 'localhost', 4),

-- Pregunta 7
('Ciencias Sociales', NULL, 'Los recursos naturales', 'Los recursos naturales son aquellos que la naturaleza nos proporciona, como el agua, los minerales, y los bosques.', NULL, NULL, NULL, '¿Qué es un recurso natural?', 'Algo creado por el hombre', 'Algo que pertenece a la tecnología', 'Algo que la naturaleza nos proporciona', 'Algo que solo se encuentra en las ciudades', 'C', 1, true, '2024-10-13 05:27:08.597681', 'admin', 'localhost', '2024-10-13 05:27:08.597681', 'admin', 'localhost', 4),

-- Pregunta 8
('Ciencias Sociales', NULL, 'El río Amazonas', 'El río Amazonas es el río más largo de Sudamérica y uno de los más caudalosos del mundo.', NULL, NULL, NULL, '¿En qué continente se encuentra el río Amazonas?', 'Asia', 'África', 'América', 'Europa', 'C', 1, true, '2024-10-13 05:28:08.597681', 'admin', 'localhost', '2024-10-13 05:28:08.597681', 'admin', 'localhost', 4),

-- Pregunta 9
('Ciencias Sociales', NULL, 'La Revolución Industrial', 'La Revolución Industrial fue un periodo de grandes cambios en la producción, desde la agricultura hasta la industria en las fábricas.', NULL, NULL, NULL, '¿Qué transformó la Revolución Industrial?', 'El sistema educativo', 'La producción agrícola', 'La producción industrial', 'La navegación', 'C', 1, true, '2024-10-13 05:29:08.597681', 'admin', 'localhost', '2024-10-13 05:29:08.597681', 'admin', 'localhost', 4),

-- Pregunta 10
('Ciencias Sociales', NULL, 'La independencia de los países', 'La independencia de los países es el proceso en el que una nación obtiene su libertad de otra, generalmente mediante una guerra o una revolución.', NULL, NULL, NULL, '¿Qué proceso permite a un país obtener su independencia?', 'Revolución', 'Ocupación', 'Asimilación', 'Colonización', 'A', 1, true, '2024-10-13 05:30:08.597681', 'admin', 'localhost', '2024-10-13 05:30:08.597681', 'admin', 'localhost', 4),

-- Pregunta 11
('Ciencias Sociales', NULL, 'Los avances tecnológicos', 'Los avances tecnológicos han permitido que la humanidad logre descubrimientos y mejoras en diversas áreas como la medicina, la agricultura y la comunicación.', NULL, NULL, NULL, '¿Qué área no ha sido afectada por los avances tecnológicos?', 'Medicina', 'Agricultura', 'Comunicación', 'Cultura', 'D', 1, true, '2024-10-13 05:31:08.597681', 'admin', 'localhost', '2024-10-13 05:31:08.597681', 'admin', 'localhost', 4),

-- Pregunta 12
('Ciencias Sociales', NULL, 'La cultura', 'La cultura es el conjunto de costumbres, creencias, y formas de vida que comparten los miembros de una sociedad.', NULL, NULL, NULL, '¿Qué forma parte de la cultura?', 'Ropa', 'Comida', 'Tradiciones', 'Todas las anteriores', 'D', 1, true, '2024-10-13 05:32:08.597681', 'admin', 'localhost', '2024-10-13 05:32:08.597681', 'admin', 'localhost', 4),

-- Pregunta 13
('Ciencias Sociales', NULL, 'El ciclo del agua', 'El ciclo del agua es el proceso continuo de movimiento del agua en la Tierra, que incluye la evaporación, la condensación y la precipitación.', NULL, NULL, NULL, '¿Cuál es una de las etapas del ciclo del agua?', 'Evaporación', 'Oxigenación', 'Arenización', 'Carbonización', 'A', 1, true, '2024-10-13 05:33:08.597681', 'admin', 'localhost', '2024-10-13 05:33:08.597681', 'admin', 'localhost', 4),

-- Pregunta 14
('Ciencias Sociales', NULL, 'La geografía', 'La geografía es la ciencia que estudia la superficie terrestre y los elementos que la componen, como montañas, ríos y océanos.', NULL, NULL, NULL, '¿Qué estudia la geografía?', 'El clima', 'Los océanos', 'La superficie terrestre', 'La biología', 'C', 1, true, '2024-10-13 05:34:08.597681', 'admin', 'localhost', '2024-10-13 05:34:08.597681', 'admin', 'localhost', 4),

-- Pregunta 15
('Ciencias Sociales', NULL, 'El sol', 'El sol es la estrella que proporciona luz y calor a la Tierra. Es fundamental para la vida en nuestro planeta.', NULL, NULL, NULL, '¿Qué es el sol?', 'Una estrella', 'Un planeta', 'Un satélite', 'Una nube', 'A', 1, true, '2024-10-13 05:35:08.597681', 'admin', 'localhost', '2024-10-13 05:35:08.597681', 'admin', 'localhost', 4),

-- Pregunta 16
('Ciencias Sociales', NULL, 'La agricultura', 'La agricultura es la actividad humana que se encarga de cultivar la tierra y criar animales para la producción de alimentos.', NULL, NULL, NULL, '¿Qué actividad se realiza en la agricultura?', 'Pescar', 'Cazar', 'Cultivar la tierra', 'Construir casas', 'C', 1, true, '2024-10-13 05:36:08.597681', 'admin', 'localhost', '2024-10-13 05:36:08.597681', 'admin', 'localhost', 4),

-- Pregunta 17
('Ciencias Sociales', NULL, 'La energía', 'La energía es la capacidad que tienen los seres vivos, máquinas o sistemas para realizar trabajos o generar cambios.', NULL, NULL, NULL, '¿Qué es la energía?', 'La capacidad para descansar', 'La capacidad para realizar trabajos', 'La capacidad para leer', 'La capacidad para dormir', 'B', 1, true, '2024-10-13 05:37:08.597681', 'admin', 'localhost', '2024-10-13 05:37:08.597681', 'admin', 'localhost', 4),

-- Pregunta 18
('Ciencias Sociales', NULL, 'Los derechos humanos', 'Los derechos humanos son principios que reconocen la dignidad y la igualdad de todos los seres humanos, sin importar su origen.', NULL, NULL, NULL, '¿Qué son los derechos humanos?', 'Principios que establecen la libertad y la igualdad', 'Reglas para el gobierno', 'Normas para las empresas', 'Instrucciones para los países', 'A', 1, true, '2024-10-13 05:38:08.597681', 'admin', 'localhost', '2024-10-13 05:38:08.597681', 'admin', 'localhost', 4),

-- Pregunta 19
('Ciencias Sociales', NULL, 'La historia', 'La historia es la ciencia que estudia los hechos y procesos que ocurrieron en el pasado.', NULL, NULL, NULL, '¿Qué estudia la historia?', 'El futuro', 'El presente', 'Los hechos del pasado', 'Los animales', 'C', 1, true, '2024-10-13 05:39:08.597681', 'admin', 'localhost', '2024-10-13 05:39:08.597681', 'admin', 'localhost', 4),

-- Pregunta 20
('Ciencias Sociales', NULL, 'Los gobiernos', 'El gobierno es el sistema o grupo de personas que tiene el poder para tomar decisiones en un país o región.', NULL, NULL, NULL, '¿Qué es el gobierno?', 'El sistema judicial', 'El sistema de salud', 'El sistema que toma decisiones en un país', 'El sistema educativo', 'C', 1, true, '2024-10-13 05:40:08.597681', 'admin', 'localhost', '2024-10-13 05:40:08.597681', 'admin', 'localhost', 4);



--PREGUNTAS IND. PARA QUINTO GRADO PRIMARIA

INSERT INTO pregunta 
("TIPO_EVALUACION", "GRUPO", "TEXTO_TITULO", "TEXTO_SUPERIOR", "TEXTO_IMAGEN", "TEXTO_INFERIOR", "ID_ARCHIVO_CARGA", "PREGUNTA", "OPCION_A", "OPCION_B", "OPCION_C", "OPCION_D", "RESPUESTA_CORRECTA", "ID_COMPETENCIA", "POSTULA_ACTIVO", "POSTULA_FECHA_CREACION", "POSTULA_USUARIO_CREACION", "POSTULA_HOST_CREACION", "POSTULA_FECHA_ACTUALIZA", "POSTULA_USUARIO_ACTUALIZA", "POSTULA_HOST_ACTUALIZA", "ID_GRADO")
VALUES
('Arte y Cultura', NULL, '¿Qué es el arte?', 'El arte es una forma de expresión humana que abarca diferentes disciplinas.', NULL, NULL, NULL, '¿Cómo se llama la técnica en la que se usa la arcilla para modelar figuras?', 'Escultura', 'Pintura', 'Música', 'Danza', 'A', 1, true, '2024-10-13 05:21:08.597681', 'admin', 'localhost', '2024-10-13 05:21:08.597681', 'admin', 'localhost', 5),
('Arte y Cultura', NULL, 'La pintura de paisajes', 'La pintura de paisajes muestra escenarios naturales y es una de las formas más antiguas de arte.', NULL, NULL, NULL, '¿Qué tipo de pintura muestra escenarios naturales?', 'Escultura', 'Muralismo', 'Paisajismo', 'Abstracción', 'C', 1, true, '2024-10-13 05:22:08.597681', 'admin', 'localhost', '2024-10-13 05:22:08.597681', 'admin', 'localhost', 5),
('Arte y Cultura', NULL, 'La música en el arte', 'La música es una forma de arte que se expresa a través de sonidos organizados.', NULL, NULL, NULL, '¿Qué instrumento musical se utiliza para crear sonidos agudos?', 'Piano', 'Guitarra', 'Violín', 'Tímpano', 'C', 1, true, '2024-10-13 05:23:08.597681', 'admin', 'localhost', '2024-10-13 05:23:08.597681', 'admin', 'localhost', 5),
('Arte y Cultura', NULL, 'El teatro', 'El teatro es una disciplina artística que involucra la actuación en vivo.', NULL, NULL, NULL, '¿Qué tipo de arte involucra la actuación en vivo?', 'Danza', 'Teatro', 'Música', 'Cine', 'B', 1, true, '2024-10-13 05:24:08.597681', 'admin', 'localhost', '2024-10-13 05:24:08.597681', 'admin', 'localhost', 5),
('Arte y Cultura', NULL, 'La danza clásica', 'La danza clásica es una de las formas de danza más formales y estructuradas.', NULL, NULL, NULL, '¿Cuál es una de las características de la danza clásica?', 'Movimientos libres', 'Estructura rígida', 'Improvisación', 'Danza en pareja', 'B', 1, true, '2024-10-13 05:25:08.597681', 'admin', 'localhost', '2024-10-13 05:25:08.597681', 'admin', 'localhost', 5),
('Arte y Cultura', NULL, 'El arte moderno', 'El arte moderno se caracteriza por la innovación y el uso de nuevas formas de expresión.', NULL, NULL, NULL, '¿Qué caracteriza al arte moderno?', 'Simetría perfecta', 'Innovación y experimentación', 'Uso de colores neutros', 'Representación exacta de la realidad', 'B', 1, true, '2024-10-13 05:26:08.597681', 'admin', 'localhost', '2024-10-13 05:26:08.597681', 'admin', 'localhost', 5),
('Arte y Cultura', NULL, 'El muralismo', 'El muralismo es una forma de arte que utiliza las paredes como lienzo.', NULL, NULL, NULL, '¿Qué tipo de arte utiliza las paredes como lienzo?', 'Escultura', 'Muralismo', 'Pintura al óleo', 'Fotografía', 'B', 1, true, '2024-10-13 05:27:08.597681', 'admin', 'localhost', '2024-10-13 05:27:08.597681', 'admin', 'localhost', 5),
('Arte y Cultura', NULL, 'El arte renacentista', 'El arte renacentista se caracteriza por su realismo y la representación exacta del cuerpo humano.', NULL, NULL, NULL, '¿Qué caracteriza al arte renacentista?', 'Uso de colores vibrantes', 'Representación exacta del cuerpo humano', 'Estilo abstracto', 'Simbolismo', 'B', 1, true, '2024-10-13 05:28:08.597681', 'admin', 'localhost', '2024-10-13 05:28:08.597681', 'admin', 'localhost', 5),
('Arte y Cultura', NULL, 'El arte abstracto', 'El arte abstracto busca representar conceptos y emociones sin recurrir a la representación fiel de la realidad.', NULL, NULL, NULL, '¿Qué representa principalmente el arte abstracto?', 'Paisajes', 'Formas geométricas', 'Emociones y conceptos', 'Figuras humanas', 'C', 1, true, '2024-10-13 05:29:08.597681', 'admin', 'localhost', '2024-10-13 05:29:08.597681', 'admin', 'localhost', 5),
('Arte y Cultura', NULL, 'La escultura', 'La escultura es una forma de arte en la que se modelan figuras tridimensionales.', NULL, NULL, NULL, '¿Qué tipo de arte consiste en modelar figuras tridimensionales?', 'Escultura', 'Pintura', 'Dibujo', 'Muralismo', 'A', 1, true, '2024-10-13 05:30:08.597681', 'admin', 'localhost', '2024-10-13 05:30:08.597681', 'admin', 'localhost', 5),
('Arte y Cultura', NULL, 'El impresionismo', 'El impresionismo es un movimiento artístico que se caracteriza por el uso de pinceladas rápidas y colores brillantes.', NULL, NULL, NULL, '¿Qué caracteriza al impresionismo?', 'Pinceladas rápidas y colores brillantes', 'Uso de líneas rectas', 'Colores oscuros y suaves', 'Pinturas abstractas', 'A', 1, true, '2024-10-13 05:31:08.597681', 'admin', 'localhost', '2024-10-13 05:31:08.597681', 'admin', 'localhost', 5),
('Arte y Cultura', NULL, 'El arte pop', 'El arte pop se inspira en los medios de comunicación de masas, como la publicidad y la cultura popular.', NULL, NULL, NULL, '¿De qué se inspira el arte pop?', 'La naturaleza', 'La cultura popular y la publicidad', 'El arte clásico', 'La arquitectura', 'B', 1, true, '2024-10-13 05:32:08.597681', 'admin', 'localhost', '2024-10-13 05:32:08.597681', 'admin', 'localhost', 5),
('Arte y Cultura', NULL, 'El arte surrealista', 'El surrealismo es un movimiento artístico que busca representar el inconsciente y lo irracional.', NULL, NULL, NULL, '¿Qué representa principalmente el arte surrealista?', 'Lo racional y lógico', 'Lo inconsciente y lo irracional', 'Paisajes naturales', 'Escenas de la vida diaria', 'B', 1, true, '2024-10-13 05:33:08.597681', 'admin', 'localhost', '2024-10-13 05:33:08.597681', 'admin', 'localhost', 5),
('Arte y Cultura', NULL, 'El arte prehistórico', 'El arte prehistórico está compuesto por las primeras representaciones visuales creadas por el ser humano.', NULL, NULL, NULL, '¿Qué caracteriza al arte prehistórico?', 'Uso de pinceles y lienzos', 'Representación de escenas cotidianas', 'Las primeras representaciones visuales', 'Uso de tecnología avanzada', 'C', 1, true, '2024-10-13 05:34:08.597681', 'admin', 'localhost', '2024-10-13 05:34:08.597681', 'admin', 'localhost', 5),
('Arte y Cultura', NULL, 'El arte en la antigüedad', 'El arte de la antigüedad se caracteriza por su simbolismo y las figuras mitológicas.', NULL, NULL, NULL, '¿Qué caracteriza al arte de la antigüedad?', 'Realismo extremo', 'Figuras mitológicas y simbolismo', 'Abstracción', 'Uso de nuevos materiales', 'B', 1, true, '2024-10-13 05:35:08.597681', 'admin', 'localhost', '2024-10-13 05:35:08.597681', 'admin', 'localhost', 5),
('Arte y Cultura', NULL, 'El arte en el Renacimiento', 'El Renacimiento fue un período artístico que promovió el renacer del arte clásico de la antigua Grecia y Roma.', NULL, NULL, NULL, '¿Qué periodo artístico promovió el renacer del arte clásico?', 'Romántico', 'Renacimiento', 'Barroco', 'Moderno', 'B', 1, true, '2024-10-13 05:36:08.597681', 'admin', 'localhost', '2024-10-13 05:36:08.597681', 'admin', 'localhost', 5),
('Arte y Cultura', NULL, 'El arte en la Edad Media', 'El arte medieval se caracteriza por su temática religiosa y el uso de la luz.', NULL, NULL, NULL, '¿Qué tema predominaba en el arte medieval?', 'Temas históricos', 'Temas religiosos', 'Temas filosóficos', 'Escenas de la vida cotidiana', 'B', 1, true, '2024-10-13 05:37:08.597681', 'admin', 'localhost', '2024-10-13 05:37:08.597681', 'admin', 'localhost', 5),
('Arte y Cultura', NULL, 'El arte contemporáneo', 'El arte contemporáneo abarca las producciones artísticas más actuales, influenciadas por la globalización y la tecnología.', NULL, NULL, NULL, '¿Qué caracteriza al arte contemporáneo?', 'Representación de la realidad de manera exacta', 'Influencias de la tecnología y la globalización', 'Uso exclusivo de materiales tradicionales', 'Enfoque en la simplicidad y el minimalismo', 'B', 1, true, '2024-10-13 05:38:08.597681', 'admin', 'localhost', '2024-10-13 05:38:08.597681', 'admin', 'localhost', 5),
('Arte y Cultura', NULL, 'El arte egipcio', 'El arte egipcio se caracteriza por la simetría, las figuras estilizadas y los colores brillantes.', NULL, NULL, NULL, '¿Qué caracteriza al arte egipcio?', 'Colores suaves y oscuros', 'Uso de figuras estilizadas y simetría', 'Representación de escenas cotidianas', 'Estilo libre y abstracto', 'B', 1, true, '2024-10-13 05:39:08.597681', 'admin', 'localhost', '2024-10-13 05:39:08.597681', 'admin', 'localhost', 5),
('Arte y Cultura', NULL, 'El arte en la Edad Moderna', 'La Edad Moderna fue un periodo en el que el arte experimentó nuevas formas de expresión como el barroco y el rococó.', NULL, NULL, NULL, '¿Qué periodo artístico apareció en la Edad Moderna?', 'Renacimiento', 'Barroco y Rococó', 'Modernismo', 'Arte abstracto', 'B', 1, true, '2024-10-13 05:40:08.597681', 'admin', 'localhost', '2024-10-13 05:40:08.597681', 'admin', 'localhost', 5);



--PREGUNTAS IND. PARA SEXTO GRADO PRIMARIA

INSERT INTO pregunta 
("TIPO_EVALUACION", "GRUPO", "TEXTO_TITULO", "TEXTO_SUPERIOR", "TEXTO_IMAGEN", "TEXTO_INFERIOR", "ID_ARCHIVO_CARGA", "PREGUNTA", "OPCION_A", "OPCION_B", "OPCION_C", "OPCION_D", "RESPUESTA_CORRECTA", "ID_COMPETENCIA", "POSTULA_ACTIVO", "POSTULA_FECHA_CREACION", "POSTULA_USUARIO_CREACION", "POSTULA_HOST_CREACION", "POSTULA_FECHA_ACTUALIZA", "POSTULA_USUARIO_ACTUALIZA", "POSTULA_HOST_ACTUALIZA", "ID_GRADO")
VALUES
('Razonamiento Matemático', NULL, 'Problema de sumas', 'Realiza la siguiente suma de números.', NULL, NULL, NULL, '¿Cuánto es 125 + 75?', '100', '150', '200', '250', 'B', 1, true, '2024-02-06 09:00:00', 'admin', 'localhost', '2024-02-06 09:00:00', 'admin', 'localhost', 6),
('Razonamiento Matemático', NULL, 'Problema de multiplicación', 'Realiza la siguiente multiplicación.', NULL, NULL, NULL, '¿Cuánto es 12 * 9?', '90', '108', '120', '135', 'B', 1, true, '2024-02-06 09:05:00', 'admin', 'localhost', '2024-02-06 09:05:00', 'admin', 'localhost', 6),
('Razonamiento Matemático', NULL, 'Problema de división', 'Resuelve la siguiente división.', NULL, NULL, NULL, '¿Cuánto es 144 ÷ 12?', '10', '12', '14', '16', 'B', 1, true, '2024-02-06 09:10:00', 'admin', 'localhost', '2024-02-06 09:10:00', 'admin', 'localhost', 6),
('Razonamiento Matemático', NULL, 'Problema de suma de fracciones', 'Resuelve la siguiente suma de fracciones.', NULL, NULL, NULL, '¿Cuánto es 1/4 + 2/4?', '1/2', '1/3', '3/4', '1', 'A', 1, true, '2024-02-06 09:15:00', 'admin', 'localhost', '2024-02-06 09:15:00', 'admin', 'localhost', 6),
('Razonamiento Matemático', NULL, 'Problema de fracciones', 'Resuelve la siguiente fracción.', NULL, NULL, NULL, '¿Cuánto es 3/5 de 25?', '12', '15', '18', '20', 'B', 1, true, '2024-02-06 09:20:00', 'admin', 'localhost', '2024-02-06 09:20:00', 'admin', 'localhost', 6),
('Razonamiento Matemático', NULL, 'Problema de resta', 'Resuelve la siguiente resta.', NULL, NULL, NULL, '¿Cuánto es 500 - 275?', '225', '200', '150', '175', 'A', 1, true, '2024-02-06 09:25:00', 'admin', 'localhost', '2024-02-06 09:25:00', 'admin', 'localhost', 6),
('Razonamiento Matemático', NULL, 'Problema de porcentaje', 'Resuelve el siguiente problema de porcentaje.', NULL, NULL, NULL, '¿Cuánto es el 20% de 250?', '50', '40', '30', '60', 'A', 1, true, '2024-02-06 09:30:00', 'admin', 'localhost', '2024-02-06 09:30:00', 'admin', 'localhost', 6),
('Razonamiento Matemático', NULL, 'Problema de suma de decimales', 'Resuelve la siguiente suma de decimales.', NULL, NULL, NULL, '¿Cuánto es 12.5 + 7.3?', '19.8', '20.2', '19.0', '18.5', 'A', 1, true, '2024-02-06 09:35:00', 'admin', 'localhost', '2024-02-06 09:35:00', 'admin', 'localhost', 6),
('Razonamiento Matemático', NULL, 'Problema de álgebra', 'Resuelve la siguiente ecuación.', NULL, NULL, NULL, '¿Cuánto es 2x + 3 = 11?', 'x = 4', 'x = 3', 'x = 2', 'x = 5', 'A', 1, true, '2024-02-06 09:40:00', 'admin', 'localhost', '2024-02-06 09:40:00', 'admin', 'localhost', 6),
('Razonamiento Matemático', NULL, 'Problema de medidas', 'Resuelve el siguiente problema de medidas.', NULL, NULL, NULL, '¿Cuántos centímetros hay en 3 metros?', '300', '350', '200', '250', 'A', 1, true, '2024-02-06 09:45:00', 'admin', 'localhost', '2024-02-06 09:45:00', 'admin', 'localhost', 6),
('Razonamiento Matemático', NULL, 'Problema de tiempo', 'Resuelve el siguiente problema de tiempo.', NULL, NULL, NULL, 'Si son las 3:00 PM, ¿qué hora será en 5 horas?', '8:00 PM', '7:00 PM', '6:00 PM', '5:00 PM', 'A', 1, true, '2024-02-06 09:50:00', 'admin', 'localhost', '2024-02-06 09:50:00', 'admin', 'localhost', 6),
('Razonamiento Matemático', NULL, 'Problema de geometría', 'Resuelve el siguiente problema de geometría.', NULL, NULL, NULL, '¿Cuánto es el área de un cuadrado con lado de 5 cm?', '25 cm²', '20 cm²', '30 cm²', '15 cm²', 'A', 1, true, '2024-02-06 09:55:00', 'admin', 'localhost', '2024-02-06 09:55:00', 'admin', 'localhost', 6),
('Razonamiento Matemático', NULL, 'Problema de velocidad', 'Resuelve el siguiente problema de velocidad.', NULL, NULL, NULL, 'Un coche viaja 100 km en 2 horas, ¿cuál es su velocidad media?', '50 km/h', '40 km/h', '60 km/h', '55 km/h', 'A', 1, true, '2024-02-06 10:00:00', 'admin', 'localhost', '2024-02-06 10:00:00', 'admin', 'localhost', 6),
('Razonamiento Matemático', NULL, 'Problema de combinaciones', 'Resuelve el siguiente problema de combinaciones.', NULL, NULL, NULL, '¿Cuántos diferentes equipos de fútbol se pueden formar con 3 jugadores de un grupo de 5?', '10', '5', '20', '15', 'A', 1, true, '2024-02-06 10:05:00', 'admin', 'localhost', '2024-02-06 10:05:00', 'admin', 'localhost', 6),
('Razonamiento Matemático', NULL, 'Problema de ecuaciones', 'Resuelve la siguiente ecuación.', NULL, NULL, NULL, '¿Cuánto es 3x + 4 = 19?', 'x = 5', 'x = 4', 'x = 3', 'x = 2', 'A', 1, true, '2024-02-06 10:10:00', 'admin', 'localhost', '2024-02-06 10:10:00', 'admin', 'localhost', 6),
('Razonamiento Matemático', NULL, 'Problema de fracciones', 'Resuelve la siguiente fracción.', NULL, NULL, NULL, '¿Qué fracción de 36 es 9?', '1/4', '1/3', '1/5', '1/6', 'B', 1, true, '2024-02-06 10:15:00', 'admin', 'localhost', '2024-02-06 10:15:00', 'admin', 'localhost', 6),
('Razonamiento Matemático', NULL, 'Problema de tiempo', 'Resuelve el siguiente problema de tiempo.', NULL, NULL, NULL, 'Si son las 7:00 AM y pasan 4 horas, ¿qué hora será?', '11:00 AM', '10:00 AM', '9:00 AM', '12:00 PM', 'A', 1, true, '2024-02-06 10:20:00', 'admin', 'localhost', '2024-02-06 10:20:00', 'admin', 'localhost', 6),
('Razonamiento Matemático', NULL, 'Problema de suma', 'Resuelve la siguiente suma.', NULL, NULL, NULL, '¿Cuánto es 320 + 180?', '500', '450', '400', '420', 'A', 1, true, '2024-02-06 10:25:00', 'admin', 'localhost', '2024-02-06 10:25:00', 'admin', 'localhost', 6),
('Razonamiento Matemático', NULL, 'Problema de resta de decimales', 'Resuelve la siguiente resta de decimales.', NULL, NULL, NULL, '¿Cuánto es 15.75 - 7.30?', '8.45', '8.60', '9.00', '9.25', 'A', 1, true, '2024-02-06 10:30:00', 'admin', 'localhost', '2024-02-06 10:30:00', 'admin', 'localhost', 6),
('Razonamiento Matemático', NULL, 'Problema de áreas de figuras geométricas', 'Resuelve el siguiente problema sobre áreas.', NULL, NULL, NULL, '¿Cuál es el área de un círculo con radio de 7 cm? (Usa π = 3.14)', '153.86 cm²', '148.00 cm²', '160.00 cm²', '145.25 cm²', 'A', 1, true, '2024-02-06 10:35:00', 'admin', 'localhost', '2024-02-06 10:35:00', 'admin', 'localhost', 6);



--PREGUNTAS IND. PARA PRIMER GRADO SECUNDARIA
INSERT INTO pregunta (
    "TIPO_EVALUACION", "GRUPO", "TEXTO_TITULO", "TEXTO_SUPERIOR", "TEXTO_IMAGEN", "TEXTO_INFERIOR", "ID_ARCHIVO_CARGA", "PREGUNTA", "OPCION_A", "OPCION_B", "OPCION_C", "OPCION_D", "RESPUESTA_CORRECTA", "ID_COMPETENCIA", "POSTULA_ACTIVO", "POSTULA_FECHA_CREACION", "POSTULA_USUARIO_CREACION", "POSTULA_HOST_CREACION", "POSTULA_FECHA_ACTUALIZA", "POSTULA_USUARIO_ACTUALIZA", "POSTULA_HOST_ACTUALIZA", "ID_GRADO"
) VALUES
('Razonamiento Verbal', NULL, 'Los sinónimos', 'Los sinónimos son palabras que tienen un significado similar.', NULL, NULL, NULL, '¿Cuál es el sinónimo de "feliz"?', 'Contento', 'Triste', 'Eufórico', 'Enojado', 'A', 1, true, '2024-10-13 05:21:08.597681', 'admin', 'localhost', '2024-10-13 05:21:08.597681', 'admin', 'localhost', 7),
('Razonamiento Verbal', NULL, 'Los antónimos', 'Los antónimos son palabras que tienen significados opuestos.', NULL, NULL, NULL, '¿Cuál es el antónimo de "alto"?', 'Bajo', 'Grande', 'Ancho', 'Pequeño', 'A', 1, true, '2024-10-13 05:21:08.597681', 'admin', 'localhost', '2024-10-13 05:21:08.597681', 'admin', 'localhost', 7),
('Razonamiento Verbal', NULL, 'La comprensión lectora', 'La comprensión lectora es la capacidad de entender lo que leemos.', NULL, NULL, NULL, '¿Qué significa "interpretar" un texto?', 'Leer de manera rápida', 'Entender el significado', 'Hacer un resumen', 'Escribir sobre el texto', 'B', 1, true, '2024-10-13 05:21:08.597681', 'admin', 'localhost', '2024-10-13 05:21:08.597681', 'admin', 'localhost', 7),
('Razonamiento Verbal', NULL, 'La lógica', 'La lógica es el estudio del razonamiento y los argumentos.', NULL, NULL, NULL, '¿Qué opción sigue en la secuencia: 2, 4, 6, ...?', '8', '7', '10', '9', 'A', 1, true, '2024-10-13 05:21:08.597681', 'admin', 'localhost', '2024-10-13 05:21:08.597681', 'admin', 'localhost', 7),
('Razonamiento Verbal', NULL, 'El significado de palabras', 'El significado de una palabra puede variar según el contexto.', NULL, NULL, NULL, '¿Qué significa "banco" en este contexto: "Voy al banco a retirar dinero"?', 'Institución financiera', 'Lugar para sentarse', 'Construcción de ladrillo', 'Lugar para guardar objetos', 'A', 1, true, '2024-10-13 05:21:08.597681', 'admin', 'localhost', '2024-10-13 05:21:08.597681', 'admin', 'localhost', 7),
('Razonamiento Verbal', NULL, 'El significado figurado', 'Algunas expresiones tienen un significado figurado o simbólico.', NULL, NULL, NULL, '¿Qué significa "romper el hielo" en una conversación?', 'Comenzar una charla', 'Terminar una conversación', 'Hablar sin sentido', 'Hablar demasiado', 'A', 1, true, '2024-10-13 05:21:08.597681', 'admin', 'localhost', '2024-10-13 05:21:08.597681', 'admin', 'localhost', 7),
('Razonamiento Verbal', NULL, 'Analogías', 'Las analogías son comparaciones entre dos cosas que tienen una relación similar.', NULL, NULL, NULL, 'Perro es a gato como niño es a ...', 'Adolescente', 'Niña', 'Adulto', 'Hombre', 'B', 1, true, '2024-10-13 05:21:08.597681', 'admin', 'localhost', '2024-10-13 05:21:08.597681', 'admin', 'localhost', 7),
('Razonamiento Verbal', NULL, 'Palabras con varias significados', 'Algunas palabras tienen múltiples significados dependiendo del contexto.', NULL, NULL, NULL, '¿Cuál de estas palabras tiene más de un significado?', 'Banco', 'Casa', 'Libro', 'Zapato', 'A', 1, true, '2024-10-13 05:21:08.597681', 'admin', 'localhost', '2024-10-13 05:21:08.597681', 'admin', 'localhost', 7),
('Razonamiento Verbal', NULL, 'La estructura del texto', 'Un texto tiene una estructura que nos ayuda a entenderlo mejor.', NULL, NULL, NULL, '¿Qué parte de un texto nos dice de qué trata?', 'Introducción', 'Conclusión', 'Desarrollo', 'Cuerpo', 'A', 1, true, '2024-10-13 05:21:08.597681', 'admin', 'localhost', '2024-10-13 05:21:08.597681', 'admin', 'localhost', 7),
('Razonamiento Verbal', NULL, 'Inferencias', 'Hacer inferencias implica leer entre líneas y sacar conclusiones.', NULL, NULL, NULL, '¿Cuál es la inferencia correcta a partir de este enunciado? "Estaba lloviendo, por lo que María llevaba paraguas."', 'María llevaba paraguas porque no quería mojarse', 'María no quería llegar tarde', 'María tenía miedo', 'María estaba enferma', 'A', 1, true, '2024-10-13 05:21:08.597681', 'admin', 'localhost', '2024-10-13 05:21:08.597681', 'admin', 'localhost', 7),
('Razonamiento Verbal', NULL, 'Oraciones incompletas', 'Una oración incompleta necesita ser completada con una palabra que tenga sentido.', NULL, NULL, NULL, 'La biblioteca está _____ de libros.', 'llena', 'vacía', 'abierta', 'cerrada', 'A', 1, true, '2024-10-13 05:21:08.597681', 'admin', 'localhost', '2024-10-13 05:21:08.597681', 'admin', 'localhost', 7),
('Razonamiento Verbal', NULL, 'Vocabulario', 'Un buen vocabulario nos ayuda a expresarnos mejor.', NULL, NULL, NULL, '¿Qué palabra es un sinónimo de "grande"?', 'Enorme', 'Pequeño', 'Rápido', 'Lento', 'A', 1, true, '2024-10-13 05:21:08.597681', 'admin', 'localhost', '2024-10-13 05:21:08.597681', 'admin', 'localhost', 7),
('Razonamiento Verbal', NULL, 'Comprehensión verbal', 'La comprensión verbal se refiere a entender lo que se lee.', NULL, NULL, NULL, '¿Cuál es el significado de "juventud"?', 'Época de la vida', 'Ropa nueva', 'Un tipo de comida', 'Un deporte', 'A', 1, true, '2024-10-13 05:21:08.597681', 'admin', 'localhost', '2024-10-13 05:21:08.597681', 'admin', 'localhost', 7),
('Razonamiento Verbal', NULL, 'Identificación de errores', 'Es importante identificar errores en las frases para mejorar el texto.', NULL, NULL, NULL, '¿Cuál es el error en la siguiente oración? "El perro corría rápidamente rápidamente."', 'Repetición de "rápidamente"', 'Falta una coma', 'Uso incorrecto de "corría"', 'Uso de "perro" en minúscula', 'A', 1, true, '2024-10-13 05:21:08.597681', 'admin', 'localhost', '2024-10-13 05:21:08.597681', 'admin', 'localhost', 7),
('Razonamiento Verbal', NULL, 'Uso de preposiciones', 'Las preposiciones nos indican la relación entre palabras.', NULL, NULL, NULL, '¿Qué preposición se utiliza en la oración: "El libro está _____ la mesa?"', 'Sobre', 'Bajo', 'Dentro', 'En', 'A', 1, true, '2024-10-13 05:21:08.597681', 'admin', 'localhost', '2024-10-13 05:21:08.597681', 'admin', 'localhost', 7),
('Razonamiento Verbal', NULL, 'Sinónimos de uso común', 'El conocimiento de sinónimos ayuda a mejorar el vocabulario.', NULL, NULL, NULL, '¿Cuál es el sinónimo de "feliz"?', 'Contento', 'Triste', 'Eufórico', 'Enojado', 'A', 1, true, '2024-10-13 05:21:08.597681', 'admin', 'localhost', '2024-10-13 05:21:08.597681', 'admin', 'localhost', 7),
('Razonamiento Verbal', NULL, 'Antónimos de uso común', 'El conocimiento de antónimos es útil para comprender mejor las palabras.', NULL, NULL, NULL, '¿Cuál es el antónimo de "bajo"?', 'Alto', 'Pequeño', 'Delgado', 'Grande', 'A', 1, true, '2024-10-13 05:21:08.597681', 'admin', 'localhost', '2024-10-13 05:21:08.597681', 'admin', 'localhost', 7),
('Razonamiento Verbal', NULL, 'La estructura de la oración', 'Entender cómo se estructuran las oraciones es fundamental para una buena comunicación.', NULL, NULL, NULL, '¿Cuál de estas oraciones está correctamente estructurada?', 'El perro corre rápidamente', 'Perro rápidamente corre el', 'Corre rápidamente perro el', 'Perro corre el rápidamente', 'A', 1, true, '2024-10-13 05:21:08.597681', 'admin', 'localhost', '2024-10-13 05:21:08.597681', 'admin', 'localhost', 7),
('Razonamiento Verbal', NULL, 'La importancia de la lectura', 'La lectura nos ayuda a mejorar nuestro razonamiento y vocabulario.', NULL, NULL, NULL, '¿Por qué es importante leer libros?', 'Para mejorar el vocabulario', 'Para dormir mejor', 'Para distraerse', 'Para evitar el estrés', 'A', 1, true, '2024-10-13 05:21:08.597681', 'admin', 'localhost', '2024-10-13 05:21:08.597681', 'admin', 'localhost', 7),
('Razonamiento Verbal', NULL, 'El significado de una frase', 'El significado de las frases depende de cómo las interpretamos.', NULL, NULL, NULL, '¿Qué significa "matar dos pájaros de un tiro"?', 'Lograr dos cosas al mismo tiempo', 'Matar a dos personas', 'Dañar algo valioso', 'Hacer algo peligroso', 'A', 1, true, '2024-10-13 05:21:08.597681', 'admin', 'localhost', '2024-10-13 05:21:08.597681', 'admin', 'localhost', 7);




--PREGUNTAS IND. PARA SEGUNDO GRADO SECUNDARIA

INSERT INTO pregunta 
("TIPO_EVALUACION", "GRUPO", "TEXTO_TITULO", "TEXTO_SUPERIOR", "TEXTO_IMAGEN", "TEXTO_INFERIOR", "ID_ARCHIVO_CARGA", "PREGUNTA", "OPCION_A", "OPCION_B", "OPCION_C", "OPCION_D", "RESPUESTA_CORRECTA", "ID_COMPETENCIA", "POSTULA_ACTIVO", "POSTULA_FECHA_CREACION", "POSTULA_USUARIO_CREACION", "POSTULA_HOST_CREACION", "POSTULA_FECHA_ACTUALIZA", "POSTULA_USUARIO_ACTUALIZA", "POSTULA_HOST_ACTUALIZA", "ID_GRADO")
VALUES
('Educación Cívica', NULL, 'Derechos y deberes de los ciudadanos', 'Los ciudadanos tienen derechos y deberes que deben ser respetados para vivir en una sociedad armoniosa.', NULL, NULL, NULL, '¿Cuál de los siguientes es un derecho de los ciudadanos?', 'Votar', 'Tener propiedades', 'Estudiar gratis', 'Ser dueño de un negocio', 'A', 1, true, '2024-10-13 05:21:08.597681', 'admin', 'localhost', '2024-10-13 05:21:08.597681', 'admin', 'localhost', 8),
('Educación Cívica', NULL, 'Participación en la democracia', 'La democracia permite la participación de los ciudadanos en el gobierno, a través del voto.', NULL, NULL, NULL, '¿Qué significa la participación en la democracia?', 'Elegir a los gobernantes', 'Vivir en una dictadura', 'Ser parte del gobierno', 'Obedecer las leyes', 'A', 1, true, '2024-10-13 05:21:08.597681', 'admin', 'localhost', '2024-10-13 05:21:08.597681', 'admin', 'localhost', 8),
('Educación Cívica', NULL, 'La familia', 'La familia es la base de la sociedad y tiene un papel fundamental en el desarrollo de los individuos.', NULL, NULL, NULL, '¿Cuál es la principal función de la familia?', 'Proteger a los hijos', 'Trabajar para el gobierno', 'Controlar la sociedad', 'Estudiar en la escuela', 'A', 1, true, '2024-10-13 05:21:08.597681', 'admin', 'localhost', '2024-10-13 05:21:08.597681', 'admin', 'localhost', 8),
('Educación Cívica', NULL, 'La paz social', 'La paz social es fundamental para el bienestar de una nación. Todos deben trabajar para preservarla.', NULL, NULL, NULL, '¿Cómo se puede fomentar la paz social?', 'Promoviendo la tolerancia', 'Ignorando los problemas sociales', 'Haciendo guerras', 'Aislándose de los demás', 'A', 1, true, '2024-10-13 05:21:08.597681', 'admin', 'localhost', '2024-10-13 05:21:08.597681', 'admin', 'localhost', 8),
('Educación Cívica', NULL, 'La importancia de la educación', 'La educación es un derecho que permite el desarrollo personal y social.', NULL, NULL, NULL, '¿Por qué es importante la educación?', 'Ayuda al crecimiento personal', 'Hace a las personas ricas', 'Solo es importante para los adultos', 'No tiene impacto en la vida', 'A', 1, true, '2024-10-13 05:21:08.597681', 'admin', 'localhost', '2024-10-13 05:21:08.597681', 'admin', 'localhost', 8),
('Educación Cívica', NULL, 'La constitución', 'La constitución es la ley suprema de un país y establece los derechos y deberes de los ciudadanos.', NULL, NULL, NULL, '¿Qué es la constitución?', 'Es la ley suprema', 'Es un libro de historia', 'Es una ley económica', 'Es un tipo de gobierno', 'A', 1, true, '2024-10-13 05:21:08.597681', 'admin', 'localhost', '2024-10-13 05:21:08.597681', 'admin', 'localhost', 8),
('Educación Cívica', NULL, 'El respeto', 'El respeto es un valor fundamental para convivir en sociedad y relacionarse de manera armónica.', NULL, NULL, NULL, '¿Por qué es importante el respeto?', 'Para vivir en armonía', 'Para ganar dinero', 'Para obtener poder', 'Para tener fama', 'A', 1, true, '2024-10-13 05:21:08.597681', 'admin', 'localhost', '2024-10-13 05:21:08.597681', 'admin', 'localhost', 8),
('Educación Cívica', NULL, 'La solidaridad', 'La solidaridad es la ayuda mutua entre las personas para alcanzar el bienestar común.', NULL, NULL, NULL, '¿Qué significa ser solidario?', 'Ayudar a los demás', 'Ignorar a los demás', 'Competir con los demás', 'Pedir ayuda siempre', 'A', 1, true, '2024-10-13 05:21:08.597681', 'admin', 'localhost', '2024-10-13 05:21:08.597681', 'admin', 'localhost', 8),
('Educación Cívica', NULL, 'La justicia', 'La justicia es un principio que busca la igualdad y la equidad entre todos los miembros de la sociedad.', NULL, NULL, NULL, '¿Qué es la justicia?', 'Igualdad ante la ley', 'Ser castigado por errores', 'Tener dinero suficiente', 'Ser respetado por los demás', 'A', 1, true, '2024-10-13 05:21:08.597681', 'admin', 'localhost', '2024-10-13 05:21:08.597681', 'admin', 'localhost', 8),
('Educación Cívica', NULL, 'La democracia', 'La democracia es el sistema de gobierno donde el poder reside en el pueblo, a través de elecciones libres.', NULL, NULL, NULL, '¿Qué es la democracia?', 'Gobierno del pueblo', 'Gobierno de un rey', 'Gobierno de una élite', 'Gobierno militar', 'A', 1, true, '2024-10-13 05:21:08.597681', 'admin', 'localhost', '2024-10-13 05:21:08.597681', 'admin', 'localhost', 8),
('Educación Cívica', NULL, 'El voto', 'El voto es el derecho que tienen los ciudadanos para elegir a sus representantes en el gobierno.', NULL, NULL, NULL, '¿Qué es el voto?', 'Es el derecho a elegir', 'Es un deber sin importancia', 'Es solo para los adultos mayores', 'Es un privilegio de los ricos', 'A', 1, true, '2024-10-13 05:21:08.597681', 'admin', 'localhost', '2024-10-13 05:21:08.597681', 'admin', 'localhost', 8),
('Educación Cívica', NULL, 'La igualdad', 'La igualdad es un principio fundamental que busca que todas las personas tengan los mismos derechos y oportunidades.', NULL, NULL, NULL, '¿Qué significa igualdad?', 'Todos tienen los mismos derechos', 'Algunos tienen más derechos', 'El que tiene más dinero tiene más derechos', 'Solo los hombres tienen derechos', 'A', 1, true, '2024-10-13 05:21:08.597681', 'admin', 'localhost', '2024-10-13 05:21:08.597681', 'admin', 'localhost', 8),
('Educación Cívica', NULL, 'El trabajo', 'El trabajo es una actividad humana que produce bienes o servicios, y es fundamental para la economía.', NULL, NULL, NULL, '¿Cuál es el principal objetivo del trabajo?', 'Producir bienes y servicios', 'Ganar dinero fácil', 'No hacer nada', 'Tener tiempo libre', 'A', 1, true, '2024-10-13 05:21:08.597681', 'admin', 'localhost', '2024-10-13 05:21:08.597681', 'admin', 'localhost', 8),
('Educación Cívica', NULL, 'El respeto a las leyes', 'Las leyes son normas que regulan la convivencia social, y deben ser respetadas por todos.', NULL, NULL, NULL, '¿Por qué es importante respetar las leyes?', 'Para mantener el orden en la sociedad', 'Para obtener poder', 'Para ganar dinero', 'Para hacer lo que queramos', 'A', 1, true, '2024-10-13 05:21:08.597681', 'admin', 'localhost', '2024-10-13 05:21:08.597681', 'admin', 'localhost', 8),
('Educación Cívica', NULL, 'El medio ambiente', 'El medio ambiente es el entorno natural en el que vivimos, y es responsabilidad de todos cuidarlo.', NULL, NULL, NULL, '¿Cómo se puede cuidar el medio ambiente?', 'No contaminando', 'Botando basura en la calle', 'Desforestando', 'Usando químicos en el agua', 'A', 1, true, '2024-10-13 05:21:08.597681', 'admin', 'localhost', '2024-10-13 05:21:08.597681', 'admin', 'localhost', 8),
('Educación Cívica', NULL, 'El diálogo', 'El diálogo es el medio para resolver conflictos de manera pacífica y con respeto entre las personas.', NULL, NULL, NULL, '¿Qué es el diálogo?', 'Una conversación para resolver problemas', 'Una discusión agresiva', 'Un monólogo', 'Gritar para imponer la razón', 'A', 1, true, '2024-10-13 05:21:08.597681', 'admin', 'localhost', '2024-10-13 05:21:08.597681', 'admin', 'localhost', 8),
('Educación Cívica', NULL, 'La tolerancia', 'La tolerancia es el respeto hacia las ideas, creencias y costumbres de los demás.', NULL, NULL, NULL, '¿Qué significa la tolerancia?', 'Respetar las diferencias', 'Imponer nuestras creencias', 'Ignorar a los demás', 'Despreciar las ideas ajenas', 'A', 1, true, '2024-10-13 05:21:08.597681', 'admin', 'localhost', '2024-10-13 05:21:08.597681', 'admin', 'localhost', 8),
('Educación Cívica', NULL, 'La equidad de género', 'La equidad de género promueve la igualdad de oportunidades y derechos entre hombres y mujeres.', NULL, NULL, NULL, '¿Qué es la equidad de género?', 'Igualdad entre hombres y mujeres', 'Que los hombres manden', 'Que las mujeres trabajen más', 'Que las mujeres no trabajen', 'A', 1, true, '2024-10-13 05:21:08.597681', 'admin', 'localhost', '2024-10-13 05:21:08.597681', 'admin', 'localhost', 8),
('Educación Cívica', NULL, 'La libertad', 'La libertad es el derecho de las personas a tomar sus propias decisiones, sin interferencia externa.', NULL, NULL, NULL, '¿Qué es la libertad?', 'El derecho de elegir sin restricciones', 'Vivir sin reglas', 'No tener responsabilidades', 'Hacer todo lo que uno quiera', 'A', 1, true, '2024-10-13 05:21:08.597681', 'admin', 'localhost', '2024-10-13 05:21:08.597681', 'admin', 'localhost', 8),
('Educación Cívica', NULL, 'El compromiso ciudadano', 'El compromiso ciudadano implica la responsabilidad de cada individuo en el desarrollo de la comunidad.', NULL, NULL, NULL, '¿Qué significa ser un ciudadano comprometido?', 'Participar activamente en la sociedad', 'Ignorar los problemas sociales', 'Evitar involucrarse en actividades cívicas', 'No preocuparse por los demás', 'A', 1, true, '2024-10-13 05:21:08.597681', 'admin', 'localhost', '2024-10-13 05:21:08.597681', 'admin', 'localhost', 8);




--PREGUNTAS IND. PARA TERCER GRADO SECUNDARIA

INSERT INTO pregunta (
    "TIPO_EVALUACION", "GRUPO", "TEXTO_TITULO", "TEXTO_SUPERIOR", "TEXTO_IMAGEN", "TEXTO_INFERIOR", "ID_ARCHIVO_CARGA", 
    "PREGUNTA", "OPCION_A", "OPCION_B", "OPCION_C", "OPCION_D", "RESPUESTA_CORRECTA", "ID_COMPETENCIA", "POSTULA_ACTIVO", 
    "POSTULA_FECHA_CREACION", "POSTULA_USUARIO_CREACION", "POSTULA_HOST_CREACION", "POSTULA_FECHA_ACTUALIZA", 
    "POSTULA_USUARIO_ACTUALIZA", "POSTULA_HOST_ACTUALIZA", "ID_GRADO"
) VALUES
('Física', NULL, 'Ley de la gravedad', 'La ley de la gravedad de Newton describe la atracción de los cuerpos hacia el centro de la Tierra.', NULL, NULL, NULL, 
'¿Cuál es la ley que describe la atracción entre los cuerpos y la Tierra?', 'Ley de la termodinámica', 'Ley de la inercia', 'Ley de la gravedad', 'Ley de la acción-reacción', 'C', 1, true, '2024-10-13 05:21:08', 'admin', 'localhost', '2024-10-13 05:21:08', 'admin', 'localhost', 9),
('Física', NULL, 'La velocidad de la luz', 'La luz viaja a una velocidad constante en el vacío.', NULL, NULL, NULL, 
'¿Cuál es la velocidad de la luz en el vacío?', '300,000 km/s', '150,000 km/s', '200,000 km/s', '350,000 km/s', 'A', 1, true, '2024-10-13 05:21:08', 'admin', 'localhost', '2024-10-13 05:21:08', 'admin', 'localhost', 9),
('Física', NULL, 'El movimiento rectilíneo', 'En un movimiento rectilíneo uniforme, la velocidad es constante.', NULL, NULL, NULL, 
'¿Qué tipo de movimiento describe una velocidad constante en línea recta?', 'Movimiento rectilíneo acelerado', 'Movimiento rectilíneo uniforme', 'Movimiento circular', 'Movimiento parabólico', 'B', 1, true, '2024-10-13 05:21:08', 'admin', 'localhost', '2024-10-13 05:21:08', 'admin', 'localhost', 9),
('Física', NULL, 'Energía cinética', 'La energía cinética depende de la masa y la velocidad de un objeto en movimiento.', NULL, NULL, NULL, 
'¿De qué depende la energía cinética de un objeto?', 'Solo de la masa', 'Solo de la velocidad', 'De la masa y la velocidad', 'De la forma del objeto', 'C', 1, true, '2024-10-13 05:21:08', 'admin', 'localhost', '2024-10-13 05:21:08', 'admin', 'localhost', 9),
('Física', NULL, 'Ley de la conservación de la energía', 'La energía no se crea ni se destruye, solo se transforma.', NULL, NULL, NULL, 
'¿Qué dice la ley de la conservación de la energía?', 'La energía se crea', 'La energía se destruye', 'La energía se conserva', 'La energía desaparece', 'C', 1, true, '2024-10-13 05:21:08', 'admin', 'localhost', '2024-10-13 05:21:08', 'admin', 'localhost', 9),
('Física', NULL, 'Temperatura y calor', 'El calor es la transferencia de energía debido a una diferencia de temperatura.', NULL, NULL, NULL, 
'¿Qué describe el calor?', 'La energía cinética de las moléculas', 'La temperatura de un objeto', 'La transferencia de energía debido a la temperatura', 'La cantidad de masa en un objeto', 'C', 1, true, '2024-10-13 05:21:08', 'admin', 'localhost', '2024-10-13 05:21:08', 'admin', 'localhost', 9),
('Física', NULL, 'Fuerza de fricción', 'La fuerza de fricción actúa en sentido opuesto al movimiento de un objeto.', NULL, NULL, NULL, 
'¿Cómo se llama la fuerza que actúa en sentido opuesto al movimiento?', 'Fuerza gravitacional', 'Fuerza de fricción', 'Fuerza centrífuga', 'Fuerza electromagnética', 'B', 1, true, '2024-10-13 05:21:08', 'admin', 'localhost', '2024-10-13 05:21:08', 'admin', 'localhost', 9),
('Física', NULL, 'Ley de la inercia', 'La inercia es la propiedad que tienen los objetos de mantener su estado de reposo o movimiento.', NULL, NULL, NULL, 
'¿Qué es la inercia?', 'La tendencia de un objeto a cambiar su forma', 'La tendencia de un objeto a mantenerse en su estado', 'La tendencia de un objeto a acelerar', 'La tendencia de un objeto a detenerse', 'B', 1, true, '2024-10-13 05:21:08', 'admin', 'localhost', '2024-10-13 05:21:08', 'admin', 'localhost', 9),
('Física', NULL, 'Ondas sonoras', 'Las ondas sonoras requieren un medio para propagarse, como el aire.', NULL, NULL, NULL, 
'¿En qué medio se propagan las ondas sonoras?', 'Solo en líquidos', 'Solo en gases', 'En sólidos, líquidos y gases', 'En el vacío', 'C', 1, true, '2024-10-13 05:21:08', 'admin', 'localhost', '2024-10-13 05:21:08', 'admin', 'localhost', 9),
('Física', NULL, 'Efecto fotoeléctrico', 'El efecto fotoeléctrico ocurre cuando la luz incide sobre un material y libera electrones.', NULL, NULL, NULL, 
'¿Qué ocurre en el efecto fotoeléctrico?', 'Se emite luz', 'Se emiten electrones', 'Se genera energía cinética', 'Se genera calor', 'B', 1, true, '2024-10-13 05:21:08', 'admin', 'localhost', '2024-10-13 05:21:08', 'admin', 'localhost', 9),
('Física', NULL, 'Lentes convergentes', 'Los lentes convergentes enfocan los rayos de luz en un solo punto.', NULL, NULL, NULL, 
'¿Qué hacen los lentes convergentes?', 'Desvían la luz en múltiples direcciones', 'Enfocan la luz en un punto', 'Bloquean la luz', 'Aceleran la luz', 'B', 1, true, '2024-10-13 05:21:08', 'admin', 'localhost', '2024-10-13 05:21:08', 'admin', 'localhost', 9),
('Física', NULL, 'Leyes de Newton', 'Las tres leyes de Newton explican el movimiento de los objetos y las fuerzas involucradas.', NULL, NULL, NULL, 
'¿Qué explica la ley de la inercia de Newton?', 'El movimiento de los cuerpos', 'El reposo de los cuerpos', 'El cambio de dirección de los cuerpos', 'La tendencia de los cuerpos a mantener su estado', 'D', 1, true, '2024-10-13 05:21:08', 'admin', 'localhost', '2024-10-13 05:21:08', 'admin', 'localhost', 9),
('Física', NULL, 'Presión atmosférica', 'La presión atmosférica es la fuerza ejercida por el aire sobre la superficie de la Tierra.', NULL, NULL, NULL, 
'¿Qué es la presión atmosférica?', 'La fuerza ejercida por el aire', 'La cantidad de aire en la atmósfera', 'La temperatura del aire', 'El volumen de aire en la atmósfera', 'A', 1, true, '2024-10-13 05:21:08', 'admin', 'localhost', '2024-10-13 05:21:08', 'admin', 'localhost', 9),
('Física', NULL, 'Ley de Coulomb', 'La ley de Coulomb describe la interacción entre dos cargas eléctricas.', NULL, NULL, NULL, 
'¿Qué describe la ley de Coulomb?', 'La interacción entre cuerpos rígidos', 'La interacción entre cargas eléctricas', 'El movimiento de cargas en un campo magnético', 'La fuerza gravitacional entre dos masas', 'B', 1, true, '2024-10-13 05:21:08', 'admin', 'localhost', '2024-10-13 05:21:08', 'admin', 'localhost', 9),
('Física', NULL, 'Trabajo y energía', 'El trabajo realizado por una fuerza es igual al cambio en la energía de un objeto.', NULL, NULL, NULL, 
'¿Qué relación existe entre trabajo y energía?', 'El trabajo no afecta la energía', 'El trabajo es igual al cambio de energía', 'El trabajo aumenta la masa', 'El trabajo reduce la temperatura', 'B', 1, true, '2024-10-13 05:21:08', 'admin', 'localhost', '2024-10-13 05:21:08', 'admin', 'localhost', 9),
('Física', NULL, 'Campos magnéticos', 'Un campo magnético es el espacio donde una fuerza magnética puede ser detectada.', NULL, NULL, NULL, 
'¿Qué es un campo magnético?', 'Un espacio donde la gravedad es más fuerte', 'Un espacio donde se detectan fuerzas magnéticas', 'Un espacio vacío', 'Un espacio donde las partículas se aceleran', 'B', 1, true, '2024-10-13 05:21:08', 'admin', 'localhost', '2024-10-13 05:21:08', 'admin', 'localhost', 9),
('Física', NULL, 'Energía potencial', 'La energía potencial depende de la posición de un objeto en un campo de fuerzas.', NULL, NULL, NULL, 
'¿De qué depende la energía potencial?', 'De la velocidad del objeto', 'De la temperatura del objeto', 'De la posición del objeto', 'De la masa del objeto', 'C', 1, true, '2024-10-13 05:21:08', 'admin', 'localhost', '2024-10-13 05:21:08', 'admin', 'localhost', 9),
('Física', NULL, 'Ondas electromagnéticas', 'Las ondas electromagnéticas se propagan a través del vacío y transportan energía.', NULL, NULL, NULL, 
'¿Qué transportan las ondas electromagnéticas?', 'Solo sonido', 'Solo calor', 'Energía', 'Materia', 'C', 1, true, '2024-10-13 05:21:08', 'admin', 'localhost', '2024-10-13 05:21:08', 'admin', 'localhost', 9),
('Física', NULL, 'Movimiento circular', 'El movimiento circular es aquel en el que un objeto se desplaza siguiendo una trayectoria circular.', NULL, NULL, NULL, 
'¿Qué caracteriza al movimiento circular?', 'La velocidad constante en línea recta', 'El objeto se mueve siguiendo una trayectoria circular', 'El objeto permanece en reposo', 'El objeto se mueve en ángulo recto', 'B', 1, true, '2024-10-13 05:21:08', 'admin', 'localhost', '2024-10-13 05:21:08', 'admin', 'localhost', 9),
('Física', NULL, 'Ley de Hooke', 'La ley de Hooke describe cómo se estira o comprime un material elástico bajo la acción de una fuerza.', NULL, NULL, NULL, 
'¿Qué describe la ley de Hooke?', 'La elasticidad de los gases', 'La relación entre fuerza y deformación en materiales elásticos', 'El movimiento de los líquidos', 'La conductividad de los materiales', 'B', 1, true, '2024-10-13 05:21:08', 'admin', 'localhost', '2024-10-13 05:21:08', 'admin', 'localhost', 9);



--PREGUNTAS IND. PARA CUARTO GRADO SECUNDARIA

INSERT INTO pregunta (
    "TIPO_EVALUACION", "GRUPO", "TEXTO_TITULO", "TEXTO_SUPERIOR", "TEXTO_IMAGEN", 
    "TEXTO_INFERIOR", "ID_ARCHIVO_CARGA", "PREGUNTA", "OPCION_A", "OPCION_B", 
    "OPCION_C", "OPCION_D", "RESPUESTA_CORRECTA", "ID_COMPETENCIA", "POSTULA_ACTIVO", 
    "POSTULA_FECHA_CREACION", "POSTULA_USUARIO_CREACION", "POSTULA_HOST_CREACION", 
    "POSTULA_FECHA_ACTUALIZA", "POSTULA_USUARIO_ACTUALIZA", "POSTULA_HOST_ACTUALIZA", 
    "ID_GRADO"
) VALUES
('Química', NULL, 'Los seres vivos', 'Todos los seres vivos tienen características comunes como la capacidad de crecer, reproducirse y reaccionar a estímulos.', NULL, NULL, NULL, '¿Qué característica es común en todos los seres vivos?', 'Nacer', 'Reproducirse', 'Respirar', 'Crecer', 'B', 1, true, '2024-10-13 05:21:08.597681', 'admin', 'localhost', '2024-10-13 05:21:08.597681', 'admin', 'localhost', 10),
('Química', NULL, 'Átomo', 'Un átomo es la unidad básica de la materia y está compuesto por protones, neutrones y electrones.', NULL, NULL, NULL, '¿Qué partícula subatómica tiene carga negativa?', 'Neutrón', 'Protón', 'Electrón', 'Núcleo', 'C', 1, true, '2024-10-13 05:21:08.597681', 'admin', 'localhost', '2024-10-13 05:21:08.597681', 'admin', 'localhost', 10),
('Química', NULL, 'Estructura del átomo', 'El núcleo atómico contiene protones y neutrones, mientras que los electrones giran alrededor de este núcleo.', NULL, NULL, NULL, '¿Dónde se encuentran los electrones en un átomo?', 'En el núcleo', 'Alrededor del núcleo', 'Dentro del núcleo', 'En el espacio vacío', 'B', 1, true, '2024-10-13 05:21:08.597681', 'admin', 'localhost', '2024-10-13 05:21:08.597681', 'admin', 'localhost', 10),
('Química', NULL, 'Tabla periódica', 'La tabla periódica organiza los elementos químicos según sus propiedades y número atómico.', NULL, NULL, NULL, '¿Qué elemento se encuentra en el grupo 1 de la tabla periódica?', 'Hidrógeno', 'Oxígeno', 'Helio', 'Carbono', 'A', 1, true, '2024-10-13 05:21:08.597681', 'admin', 'localhost', '2024-10-13 05:21:08.597681', 'admin', 'localhost', 10),
('Química', NULL, 'Reacciones químicas', 'Las reacciones químicas son procesos en los que se transforman sustancias químicas en nuevas sustancias.', NULL, NULL, NULL, '¿Qué se forma en una reacción química?', 'Materia', 'Energía', 'Nuevas sustancias', 'Átomos', 'C', 1, true, '2024-10-13 05:21:08.597681', 'admin', 'localhost', '2024-10-13 05:21:08.597681', 'admin', 'localhost', 10),
('Química', NULL, 'Ley de conservación de la masa', 'La masa no se crea ni se destruye, solo se transforma durante las reacciones químicas.', NULL, NULL, NULL, '¿Qué afirma la ley de conservación de la masa?', 'La masa desaparece', 'La masa se conserva', 'La masa se transforma en energía', 'La masa se reduce', 'B', 1, true, '2024-10-13 05:21:08.597681', 'admin', 'localhost', '2024-10-13 05:21:08.597681', 'admin', 'localhost', 10),
('Química', NULL, 'Composición del agua', 'El agua está formada por moléculas compuestas por dos átomos de hidrógeno y uno de oxígeno.', NULL, NULL, NULL, '¿Qué elementos componen una molécula de agua?', 'Hidrógeno y oxígeno', 'Hidrógeno y nitrógeno', 'Oxígeno y carbono', 'Carbono y hidrógeno', 'A', 1, true, '2024-10-13 05:21:08.597681', 'admin', 'localhost', '2024-10-13 05:21:08.597681', 'admin', 'localhost', 10),
('Química', NULL, 'Solución ácida', 'Una solución ácida tiene un pH menor a 7.', NULL, NULL, NULL, '¿Cuál es el pH de una solución ácida?', 'Mayor a 7', 'Igual a 7', 'Menor a 7', 'No se puede determinar', 'C', 1, true, '2024-10-13 05:21:08.597681', 'admin', 'localhost', '2024-10-13 05:21:08.597681', 'admin', 'localhost', 10),
('Química', NULL, 'Ácidos y bases', 'Los ácidos y las bases tienen propiedades opuestas. Los ácidos tienen sabor agrio y las bases tienen sabor amargo.', NULL, NULL, NULL, '¿Qué propiedad caracteriza a los ácidos?', 'Sabor dulce', 'Sabor amargo', 'Sabor salado', 'Sabor agrio', 'D', 1, true, '2024-10-13 05:21:08.597681', 'admin', 'localhost', '2024-10-13 05:21:08.597681', 'admin', 'localhost', 10),
('Química', NULL, 'Energía química', 'La energía química es la energía almacenada en los enlaces de los átomos y moléculas.', NULL, NULL, NULL, '¿Qué tipo de energía está almacenada en los enlaces químicos?', 'Energía eléctrica', 'Energía térmica', 'Energía química', 'Energía mecánica', 'C', 1, true, '2024-10-13 05:21:08.597681', 'admin', 'localhost', '2024-10-13 05:21:08.597681', 'admin', 'localhost', 10),
('Química', NULL, 'Sustancias puras', 'Las sustancias puras están formadas por un solo tipo de molécula.', NULL, NULL, NULL, '¿Qué caracteriza a una sustancia pura?', 'Está compuesta por varios tipos de moléculas', 'Está formada por un solo tipo de molécula', 'Es siempre líquida', 'Es siempre gaseosa', 'B', 1, true, '2024-10-13 05:21:08.597681', 'admin', 'localhost', '2024-10-13 05:21:08.597681', 'admin', 'localhost', 10),
('Química', NULL, 'Estado sólido', 'En el estado sólido, las partículas están muy juntas y apenas se mueven.', NULL, NULL, NULL, '¿Cómo se encuentran las partículas en un sólido?', 'Muy separadas', 'Unidas pero con movimiento', 'Muy juntas y casi sin movimiento', 'Aisladas', 'C', 1, true, '2024-10-13 05:21:08.597681', 'admin', 'localhost', '2024-10-13 05:21:08.597681', 'admin', 'localhost', 10),
('Química', NULL, 'Estado líquido', 'En el estado líquido, las partículas tienen algo de libertad de movimiento, pero siguen estando unidas.', NULL, NULL, NULL, '¿Cómo se encuentran las partículas en un líquido?', 'Muy juntas', 'Muy separadas', 'Unidas pero con algo de libertad', 'En total movimiento', 'C', 1, true, '2024-10-13 05:21:08.597681', 'admin', 'localhost', '2024-10-13 05:21:08.597681', 'admin', 'localhost', 10),
('Química', NULL, 'Estado gaseoso', 'En el estado gaseoso, las partículas se encuentran muy separadas y en continuo movimiento.', NULL, NULL, NULL, '¿Cómo se encuentran las partículas en un gas?', 'Muy juntas', 'En total movimiento y muy separadas', 'Unidas pero con algo de libertad', 'Aisladas y en reposo', 'B', 1, true, '2024-10-13 05:21:08.597681', 'admin', 'localhost', '2024-10-13 05:21:08.597681', 'admin', 'localhost', 10),
('Química', NULL, 'Mezcla homogénea', 'Una mezcla homogénea tiene una composición uniforme en toda su extensión.', NULL, NULL, NULL, '¿Cómo es la composición de una mezcla homogénea?', 'Uniforme en toda su extensión', 'Diferente en diferentes partes', 'No tiene composición', 'No tiene componentes', 'A', 1, true, '2024-10-13 05:21:08.597681', 'admin', 'localhost', '2024-10-13 05:21:08.597681', 'admin', 'localhost', 10),
('Química', NULL, 'Solución saturada', 'Una solución saturada contiene la mayor cantidad posible de soluto a una temperatura determinada.', NULL, NULL, NULL, '¿Qué caracteriza a una solución saturada?', 'Contiene el máximo de soluto posible', 'No tiene soluto', 'Tiene soluto en exceso', 'Tiene soluto muy poco', 'A', 1, true, '2024-10-13 05:21:08.597681', 'admin', 'localhost', '2024-10-13 05:21:08.597681', 'admin', 'localhost', 10),
('Química', NULL, 'Ley de los gases', 'La ley de los gases describe cómo se comportan los gases bajo diferentes condiciones de temperatura y presión.', NULL, NULL, NULL, '¿Qué describe la ley de los gases?', 'El comportamiento de los líquidos', 'El comportamiento de los gases', 'El comportamiento de los sólidos', 'El comportamiento de los átomos', 'B', 1, true, '2024-10-13 05:21:08.597681', 'admin', 'localhost', '2024-10-13 05:21:08.597681', 'admin', 'localhost', 10),
('Química', NULL, 'Cambios físicos', 'Un cambio físico no altera la composición de las sustancias, solo cambia su forma o estado.', NULL, NULL, NULL, '¿Cuál es un ejemplo de cambio físico?', 'Rompimiento de un vidrio', 'Quemar madera', 'Cocinar un huevo', 'Oxidar un metal', 'A', 1, true, '2024-10-13 05:21:08.597681', 'admin', 'localhost', '2024-10-13 05:21:08.597681', 'admin', 'localhost', 10),
('Química', NULL, 'Reacciones exotérmicas', 'Las reacciones exotérmicas liberan energía en forma de calor.', NULL, NULL, NULL, '¿Qué sucede en una reacción exotérmica?', 'Se absorbe energía', 'Se libera energía', 'No hay cambio de energía', 'Se libera luz', 'B', 1, true, '2024-10-13 05:21:08.597681', 'admin', 'localhost', '2024-10-13 05:21:08.597681', 'admin', 'localhost', 10),
('Química', NULL, 'Propiedades de los ácidos', 'Los ácidos tienen un pH menor a 7 y reaccionan con las bases para formar sales.', NULL, NULL, NULL, '¿Qué caracteriza a los ácidos?', 'Tienen sabor dulce', 'Tienen pH mayor a 7', 'Son corrosivos y tienen sabor agrio', 'Son neutros', 'C', 1, true, '2024-10-13 05:21:08.597681', 'admin', 'localhost', '2024-10-13 05:21:08.597681', 'admin', 'localhost', 10);



--PREGUNTAS IND. PARA QUINTO GRADO SECUNDARIA

INSERT INTO pregunta (
    "TIPO_EVALUACION", "GRUPO", "TEXTO_TITULO", "TEXTO_SUPERIOR", "TEXTO_IMAGEN", "TEXTO_INFERIOR", 
    "ID_ARCHIVO_CARGA", "PREGUNTA", "OPCION_A", "OPCION_B", "OPCION_C", "OPCION_D", "RESPUESTA_CORRECTA", 
    "ID_COMPETENCIA", "POSTULA_ACTIVO", "POSTULA_FECHA_CREACION", "POSTULA_USUARIO_CREACION", 
    "POSTULA_HOST_CREACION", "POSTULA_FECHA_ACTUALIZA", "POSTULA_USUARIO_ACTUALIZA", "POSTULA_HOST_ACTUALIZA", 
    "ID_GRADO"
) 
VALUES
('Biología', NULL, 'Los seres vivos', 'Todos los seres vivos tienen características comunes como la capacidad de crecer, reproducirse y reaccionar a estímulos.', NULL, NULL, NULL, '¿Qué característica es común en todos los seres vivos?', 'Nacer', 'Reproducirse', 'Respirar', 'Crecer', 'B', 1, true, '2024-10-13 05:21:08.597681', 'admin', 'localhost', '2024-10-13 05:21:08.597681', 'admin', 'localhost', 11),
('Biología', NULL, 'Células', 'Las células son la unidad básica de la vida. Pueden ser de diferentes tipos según su función.', NULL, NULL, NULL, '¿Cuál es la unidad básica de la vida?', 'Órgano', 'Tejido', 'Célula', 'Sistema', 'C', 1, true, '2024-10-13 05:21:08.597681', 'admin', 'localhost', '2024-10-13 05:21:08.597681', 'admin', 'localhost', 11),
('Biología', NULL, 'Fotosíntesis', 'La fotosíntesis es el proceso mediante el cual las plantas convierten la luz solar en energía.', NULL, NULL, NULL, '¿Qué proceso realizan las plantas para producir energía?', 'Respiración', 'Fotosíntesis', 'Digestión', 'Reproducción', 'B', 1, true, '2024-10-13 05:21:08.597681', 'admin', 'localhost', '2024-10-13 05:21:08.597681', 'admin', 'localhost', 11),
('Biología', NULL, 'Reproducción', 'La reproducción sexual involucra la unión de células sexuales de dos individuos.', NULL, NULL, NULL, '¿Qué tipo de reproducción involucra células sexuales de dos individuos?', 'Asexual', 'Sexual', 'Vegetativa', 'Clonación', 'B', 1, true, '2024-10-13 05:21:08.597681', 'admin', 'localhost', '2024-10-13 05:21:08.597681', 'admin', 'localhost', 11),
('Biología', NULL, 'Respiración celular', 'La respiración celular es el proceso por el cual las células obtienen energía de la glucosa.', NULL, NULL, NULL, '¿Cuál es el proceso mediante el cual las células obtienen energía?', 'Fotosíntesis', 'Respiración celular', 'Fermentación', 'Digestión', 'B', 1, true, '2024-10-13 05:21:08.597681', 'admin', 'localhost', '2024-10-13 05:21:08.597681', 'admin', 'localhost', 11),
('Biología', NULL, 'ADN', 'El ADN es la molécula que contiene la información genética en los seres vivos.', NULL, NULL, NULL, '¿Qué molécula contiene la información genética en los seres vivos?', 'ARN', 'ADN', 'Proteínas', 'Carbohidratos', 'B', 1, true, '2024-10-13 05:21:08.597681', 'admin', 'localhost', '2024-10-13 05:21:08.597681', 'admin', 'localhost', 11),
('Biología', NULL, 'Evolución', 'La teoría de la evolución explica cómo las especies cambian a lo largo del tiempo debido a factores como la selección natural.', NULL, NULL, NULL, '¿Qué proceso explica cómo las especies cambian a lo largo del tiempo?', 'Reproducción', 'Evolución', 'Desarrollo', 'Adaptación', 'B', 1, true, '2024-10-13 05:21:08.597681', 'admin', 'localhost', '2024-10-13 05:21:08.597681', 'admin', 'localhost', 11),
('Biología', NULL, 'Órganos', 'Los órganos son estructuras que realizan funciones específicas dentro del cuerpo de los seres vivos.', NULL, NULL, NULL, '¿Qué son los órganos?', 'Estructuras celulares', 'Estructuras que realizan funciones específicas', 'Partes del sistema nervioso', 'Elementos del sistema digestivo', 'B', 1, true, '2024-10-13 05:21:08.597681', 'admin', 'localhost', '2024-10-13 05:21:08.597681', 'admin', 'localhost', 11),
('Biología', NULL, 'Sistema circulatorio', 'El sistema circulatorio transporta sangre a través del cuerpo, llevando nutrientes y oxígeno a las células.', NULL, NULL, NULL, '¿Qué transporta el sistema circulatorio?', 'Oxígeno', 'Sangre', 'Nutrientes', 'Líquidos', 'B', 1, true, '2024-10-13 05:21:08.597681', 'admin', 'localhost', '2024-10-13 05:21:08.597681', 'admin', 'localhost', 11),
('Biología', NULL, 'Digestión', 'La digestión es el proceso mediante el cual los seres vivos descomponen los alimentos para obtener nutrientes.', NULL, NULL, NULL, '¿Qué proceso descompone los alimentos en los seres vivos?', 'Respiración', 'Digestión', 'Circulación', 'Reproducción', 'B', 1, true, '2024-10-13 05:21:08.597681', 'admin', 'localhost', '2024-10-13 05:21:08.597681', 'admin', 'localhost', 11),
('Biología', NULL, 'Sistema nervioso', 'El sistema nervioso coordina las respuestas del cuerpo a los estímulos del ambiente.', NULL, NULL, NULL, '¿Qué sistema coordina las respuestas del cuerpo?', 'Digestivo', 'Nervioso', 'Circulatorio', 'Respiratorio', 'B', 1, true, '2024-10-13 05:21:08.597681', 'admin', 'localhost', '2024-10-13 05:21:08.597681', 'admin', 'localhost', 11),
('Biología', NULL, 'Hormonas', 'Las hormonas son sustancias químicas que regulan diversas funciones en el cuerpo.', NULL, NULL, NULL, '¿Qué son las hormonas?', 'Proteínas', 'Sustancias químicas reguladoras', 'Enzimas', 'Nutrientes', 'B', 1, true, '2024-10-13 05:21:08.597681', 'admin', 'localhost', '2024-10-13 05:21:08.597681', 'admin', 'localhost', 11),
('Biología', NULL, 'Clasificación de los seres vivos', 'Los seres vivos se clasifican en diferentes reinos según sus características.', NULL, NULL, NULL, '¿Cómo se clasifican los seres vivos?', 'Por su color', 'Por su tamaño', 'Por sus características', 'Por su ubicación', 'C', 1, true, '2024-10-13 05:21:08.597681', 'admin', 'localhost', '2024-10-13 05:21:08.597681', 'admin', 'localhost', 11),
('Biología', NULL, 'El ADN', 'El ADN se encuentra en el núcleo de las células y es la base para la transmisión de los caracteres hereditarios.', NULL, NULL, NULL, '¿Dónde se encuentra el ADN?', 'En el citoplasma', 'En el núcleo', 'En la membrana celular', 'En los mitocondrias', 'B', 1, true, '2024-10-13 05:21:08.597681', 'admin', 'localhost', '2024-10-13 05:21:08.597681', 'admin', 'localhost', 11),
('Biología', NULL, 'Ácidos nucleicos', 'Los ácidos nucleicos son macromoléculas que contienen la información genética de los seres vivos.', NULL, NULL, NULL, '¿Qué contienen los ácidos nucleicos?', 'Energía', 'Información genética', 'Nutrientes', 'Proteínas', 'B', 1, true, '2024-10-13 05:21:08.597681', 'admin', 'localhost', '2024-10-13 05:21:08.597681', 'admin', 'localhost', 11),
('Biología', NULL, 'Fotosíntesis', 'Las plantas realizan la fotosíntesis para producir su propio alimento.', NULL, NULL, NULL, '¿Qué producen las plantas en la fotosíntesis?', 'Oxígeno', 'Glucosa', 'Proteínas', 'Ácidos nucleicos', 'B', 1, true, '2024-10-13 05:21:08.597681', 'admin', 'localhost', '2024-10-13 05:21:08.597681', 'admin', 'localhost', 11),
('Biología', NULL, 'Enzimas', 'Las enzimas son proteínas que aceleran las reacciones químicas en los seres vivos.', NULL, NULL, NULL, '¿Qué función tienen las enzimas?', 'Disminuir la temperatura', 'Acelerar reacciones químicas', 'Descomponer alimentos', 'Regular el sistema nervioso', 'B', 1, true, '2024-10-13 05:21:08.597681', 'admin', 'localhost', '2024-10-13 05:21:08.597681', 'admin', 'localhost', 11),
('Biología', NULL, 'Excreción', 'La excreción es el proceso por el cual los seres vivos eliminan los desechos de su cuerpo.', NULL, NULL, NULL, '¿Qué proceso eliminan los desechos del cuerpo?', 'Respiración', 'Excreción', 'Digestión', 'Reproducción', 'B', 1, true, '2024-10-13 05:21:08.597681', 'admin', 'localhost', '2024-10-13 05:21:08.597681', 'admin', 'localhost', 11),
('Biología', NULL, 'Células vegetales', 'Las células vegetales contienen cloroplastos que permiten la fotosíntesis.', NULL, NULL, NULL, '¿Qué organelo permite la fotosíntesis en las células vegetales?', 'Mitocondria', 'Cloroplasto', 'Ribosoma', 'Núcleo', 'B', 1, true, '2024-10-13 05:21:08.597681', 'admin', 'localhost', '2024-10-13 05:21:08.597681', 'admin', 'localhost', 11),
('Biología', NULL, 'Teoría celular', 'La teoría celular establece que todos los seres vivos están formados por células.', NULL, NULL, NULL, '¿Qué establece la teoría celular?', 'Que las células son el núcleo de los organismos', 'Que los seres vivos están formados por células', 'Que las células no tienen núcleo', 'Que las células son invisibles', 'B', 1, true, '2024-10-13 05:21:08.597681', 'admin', 'localhost', '2024-10-13 05:21:08.597681', 'admin', 'localhost', 11);






