ALTER TABLE competencia
DROP COLUMN "POSTULA_ACTIVO",
DROP COLUMN "POSTULA_FECHA_CREACION",
DROP COLUMN "POSTULA_USUARIO_CREACION",
DROP COLUMN "POSTULA_HOST_CREACION",
DROP COLUMN "POSTULA_FECHA_ACTUALIZA",
DROP COLUMN "POSTULA_USUARIO_ACTUALIZA",
DROP COLUMN "POSTULA_HOST_ACTUALIZA";

ALTER TABLE criterio_evaluacion
DROP COLUMN "POSTULA_ACTIVO",
DROP COLUMN "POSTULA_FECHA_CREACION",
DROP COLUMN "POSTULA_USUARIO_CREACION",
DROP COLUMN "POSTULA_HOST_CREACION",
DROP COLUMN "POSTULA_FECHA_ACTUALIZA",
DROP COLUMN "POSTULA_USUARIO_ACTUALIZA",
DROP COLUMN "POSTULA_HOST_ACTUALIZA";

ALTER TABLE postulante
DROP COLUMN "POSTULA_ACTIVO",
DROP COLUMN "POSTULA_FECHA_CREACION",
DROP COLUMN "POSTULA_USUARIO_CREACION",
DROP COLUMN "POSTULA_HOST_CREACION",
DROP COLUMN "POSTULA_FECHA_ACTUALIZA",
DROP COLUMN "POSTULA_USUARIO_ACTUALIZA",
DROP COLUMN "POSTULA_HOST_ACTUALIZA";

ALTER TABLE pregunta
DROP COLUMN "POSTULA_ACTIVO",
DROP COLUMN "POSTULA_FECHA_CREACION",
DROP COLUMN "POSTULA_USUARIO_CREACION",
DROP COLUMN "POSTULA_HOST_CREACION",
DROP COLUMN "POSTULA_FECHA_ACTUALIZA",
DROP COLUMN "POSTULA_USUARIO_ACTUALIZA",
DROP COLUMN "POSTULA_HOST_ACTUALIZA";

ALTER TABLE examen_generado
DROP COLUMN "POSTULA_ACTIVO",
DROP COLUMN "POSTULA_FECHA_CREACION",
DROP COLUMN "POSTULA_USUARIO_CREACION",
DROP COLUMN "POSTULA_HOST_CREACION",
DROP COLUMN "POSTULA_FECHA_ACTUALIZA",
DROP COLUMN "POSTULA_USUARIO_ACTUALIZA",
DROP COLUMN "POSTULA_HOST_ACTUALIZA";