CREATE TABLE eventos (
    "ID_EVENTO" SERIAL PRIMARY KEY,
    "TITULO" VARCHAR(255),
    "IMAGEN_DESKTOP" VARCHAR(255),
    "IMAGEN_MOBILE" VARCHAR(255),
    "ALT_IMAGEN_DESKTOP" VARCHAR(255),
    "ALT_IMAGEN_MOBILE" VARCHAR(255),
    "URL" VARCHAR(255),
    "PRIORIDAD" INTEGER,
    "ABRIR_NUEVA_PAGINA" BOOLEAN,
    "TIPO_DE_EVENTO" VARCHAR(50),
    "CATEGORIA_EVENTO" VARCHAR(100),
    "FECHA_DE_INICIO" DATE,
    "HORA_DE_INICIO" TIME,
    "FECHA_DE_FIN" DATE,
    "HORA_DE_FIN" TIME,
    "FECHA_INICIO_EVENTO" DATE,
    "HORA_INICIO_EVENTO" TIME,
    "FECHA_FIN_EVENTO" DATE,
    "NOMBRE_BOTON" VARCHAR(255),
    "CAPACIDAD" INTEGER,
    "DESCRIPCION" TEXT
);

CREATE TABLE ubicaciones_evento (
    "ID_UBICACION_EVENTO" SERIAL PRIMARY KEY,
    "EVENTO_ID" INTEGER REFERENCES eventos("ID_EVENTO"),
    "LATITUD" DECIMAL(9, 6),
    "LONGITUD" DECIMAL(9, 6),
    "DIRECCION" VARCHAR(255),
    "NOMBRE" VARCHAR(255),
    "URL" TEXT,
    "URL_MOBILE" TEXT
);
