INSERT INTO pregunta (
    "TIPO_EVALUACION", "GRUPO", "TEXTO_TITULO", "TEXTO_SUPERIOR", "TEXTO_IMAGEN", "TEXTO_INFERIOR", "ID_ARCHIVO_CARGA", "PREGUNTA", "OPCION_A", "OPCION_B", "OPCION_C", "OPCION_D", "RESPUESTA_CORRECTA", "ID_COMPETENCIA", "ID_GRADO"
) VALUES
    ('COMPRENSIÓN LECTORA', '101', 'El zorro y el cuervo', 'Un día, un cuervo encontró un pedazo de queso y lo tomó con su pico. Se posó sobre la rama de un árbol para comerlo, pero un astuto zorro lo vio y se acercó. “¡Qué hermoso eres, cuervo! Si tu voz es tan linda como tu apariencia, serás el rey de los pájaros”, dijo el zorro.', 'https://res.cloudinary.com/djp7gmsgk/image/upload/v1740876632/el-cuervo-y-la-zorra_rfbcz8.jpg', 'El cuervo, halagado, quiso cantar para demostrarlo y, al abrir su pico, el queso cayó. Rápidamente, el zorro lo tomó y se lo comió, diciendo: “No creas en palabras halagadoras sin pensar en su intención.”', NULL, '¿Cuál es la enseñanza de la fábula?', 'No confiar en extraños', 'Ser siempre amable con los demás', 'No dejarse engañar por los halagos', 'Los cuervos no pueden cantar', 'C', 1, 1),
    ('COMPRENSIÓN LECTORA', '101', 'El zorro y el cuervo', NULL, 'https://res.cloudinary.com/djp7gmsgk/image/upload/v1740876632/el-cuervo-y-la-zorra_rfbcz8.jpg', NULL, NULL, '¿Por qué el zorro elogió al cuervo?', 'Porque el cuervo era su amigo', 'Porque realmente admiraba su belleza', 'Para engañarlo y conseguir el queso', 'Porque le gustaba su canto', 'C', 1, 1),
    ('COMPRENSIÓN LECTORA', '101', 'El zorro y el cuervo', NULL, 'https://res.cloudinary.com/djp7gmsgk/image/upload/v1740876632/el-cuervo-y-la-zorra_rfbcz8.jpg', NULL, NULL, '¿Qué hizo el cuervo cuando escuchó los elogios del zorro?', 'Cantó inmediatamente', 'Se sintió halagado y abrió su pico', 'Ignoró al zorro y siguió comiendo', 'Se fue volando', 'B', 1, 1),
    ('COMPRENSIÓN LECTORA', '101', 'El zorro y el cuervo', NULL, 'https://res.cloudinary.com/djp7gmsgk/image/upload/v1740876632/el-cuervo-y-la-zorra_rfbcz8.jpg', NULL, NULL, '¿Qué sucedió cuando el cuervo abrió su pico para cantar?', 'El queso cayó y el zorro lo tomó', 'El cuervo cantó y el zorro se fue', 'El zorro aplaudió el canto del cuervo', 'El cuervo se tragó el queso', 'A', 1, 1),
    ('COMPRENSIÓN LECTORA', '101', 'El zorro y el cuervo', NULL, 'https://res.cloudinary.com/djp7gmsgk/image/upload/v1740876632/el-cuervo-y-la-zorra_rfbcz8.jpg', NULL, NULL, '¿Cómo se sintió el cuervo al final de la historia?', 'Alegre por los elogios recibidos', 'Triste y engañado', 'Enfadado con el zorro', 'Orgulloso de su canto', 'B', 1, 1),

('COMPRENSIÓN LECTORA', '102', 'El conejo y la tortuga', 
 'Un conejo y una tortuga decidieron competir en una carrera. El conejo, seguro de su velocidad, corrió rápido y luego se detuvo a descansar, mientras que la tortuga avanzaba lentamente pero sin detenerse.', 
 'https://lh3.googleusercontent.com/d/16Kb_7n3skDHMvv8Y6sX5qC3MPcOwtZ0s=w500-h500', 
 'Cuando el conejo despertó, la tortuga ya estaba llegando a la meta y ganó la carrera. El conejo aprendió que la constancia y el esfuerzo son más importantes que la velocidad.', 
 NULL, '¿Cuál es la enseñanza principal de la fábula?', 
 'Siempre hay que correr rápido', 'La tortuga es más fuerte que el conejo', 
 'La constancia y el esfuerzo son más importantes', 'Nunca debes competir con un conejo', 
 'C', 1, 1),
('COMPRENSIÓN LECTORA', '102', 'El conejo y la tortuga', NULL, 
 'https://lh3.googleusercontent.com/d/16Kb_7n3skDHMvv8Y6sX5qC3MPcOwtZ0s=w500-h500', NULL, 
 NULL, '¿Por qué el conejo perdió la carrera?', 
 'Porque la tortuga corrió más rápido', 'Porque se confió y decidió descansar', 
 'Porque se lastimó en el camino', 'Porque la tortuga hizo trampa', 
 'B', 1, 1),
('COMPRENSIÓN LECTORA', '102', 'El conejo y la tortuga', NULL, 
 'https://lh3.googleusercontent.com/d/16Kb_7n3skDHMvv8Y6sX5qC3MPcOwtZ0s=w500-h500', NULL, 
 NULL, '¿Cómo avanzaba la tortuga durante la carrera?', 
 'Muy rápido', 'Lenta pero sin detenerse', 'Saltando entre las piedras', 'Caminando hacia atrás', 
 'B', 1, 1),
('COMPRENSIÓN LECTORA', '102', 'El conejo y la tortuga', NULL, 
 'https://lh3.googleusercontent.com/d/16Kb_7n3skDHMvv8Y6sX5qC3MPcOwtZ0s=w500-h500', NULL, 
 NULL, '¿Qué hizo el conejo después de adelantar a la tortuga?', 
 'Siguió corriendo hasta la meta', 'Decidió descansar y se quedó dormido', 
 'Volvió para ayudar a la tortuga', 'Se distrajo mirando el paisaje', 
 'B', 1, 1),
('COMPRENSIÓN LECTORA', '102', 'El conejo y la tortuga', NULL, 
 'https://lh3.googleusercontent.com/d/16Kb_7n3skDHMvv8Y6sX5qC3MPcOwtZ0s=w500-h500', NULL, 
 NULL, '¿Cómo se sintió la tortuga al ganar la carrera?', 
 'Triste porque el conejo perdió', 'Orgullosa de su esfuerzo', 
 'Asustada porque el conejo corrió muy rápido', 'Enojada con el conejo', 
 'B', 1, 1),

('COMPRENSIÓN LECTORA', '103', 'El león y el ratón', 
 'Un día, un león dormía plácidamente cuando un ratón comenzó a correr sobre él. El león se despertó y atrapó al pequeño ratón con sus garras. “¿Por qué me molestas?”, rugió el león.', 
 'https://lh3.googleusercontent.com/d/1E4E8WH33mcUEZNxugQjhA4R2PP8lsncv=w500-h500', 
 'El ratón suplicó por su vida y prometió que algún día podría ayudar al león. El león se rió, pero lo dejó ir. Días después, el león quedó atrapado en una red, y el ratón la mordió hasta liberarlo.', 
 NULL, '¿Qué le prometió el ratón al león cuando fue atrapado?', 
 'Que nunca más lo molestaría', 'Que algún día podría ayudarlo', 'Que se convertiría en su amigo', 'Que le traería comida', 'B', 1, 1),
('COMPRENSIÓN LECTORA', '103', 'El león y el ratón', 
 NULL, 'https://lh3.googleusercontent.com/d/1E4E8WH33mcUEZNxugQjhA4R2PP8lsncv=w500-h500', NULL, 
 NULL, '¿Cómo reaccionó el león cuando el ratón le dijo que algún día podría ayudarlo?', 
 'Se rió y no le creyó', 'Se enojó y lo castigó', 'Lo dejó ir inmediatamente', 'Le pidió que lo ayudara', 'A', 1, 1),
('COMPRENSIÓN LECTORA', '103', 'El león y el ratón', 
 NULL, 'https://lh3.googleusercontent.com/d/1E4E8WH33mcUEZNxugQjhA4R2PP8lsncv=w500-h500', NULL, 
 NULL, '¿Qué le sucedió al león después de dejar ir al ratón?', 
 'Quedó atrapado en una red', 'Se hizo amigo del ratón', 'Olvidó lo que pasó', 'Se fue a cazar', 'A', 1, 1),
('COMPRENSIÓN LECTORA', '103', 'El león y el ratón', 
 NULL, 'https://lh3.googleusercontent.com/d/1E4E8WH33mcUEZNxugQjhA4R2PP8lsncv=w500-h500', NULL, 
 NULL, '¿Cómo ayudó el ratón al león cuando quedó atrapado?', 
 'Llamó a otros animales', 'Mordió la red hasta liberarlo', 'Le pidió ayuda a un cazador', 'Le trajo comida mientras estaba atrapado', 'B', 1, 1),
('COMPRENSIÓN LECTORA', '103', 'El león y el ratón', 
 NULL, 'https://lh3.googleusercontent.com/d/1E4E8WH33mcUEZNxugQjhA4R2PP8lsncv=w500-h500', NULL, 
 NULL, '¿Cuál es la enseñanza de esta fábula?', 
 'Solo los animales grandes pueden ayudar', 'Nunca molestar a un león dormido', 'La amabilidad puede ser recompensada', 'Siempre hay que correr rápido', 'C', 1, 1),

('COMPRENSIÓN LECTORA', '104', 'La cigarra y la hormiga', 
	'En un cálido día de verano, una cigarra cantaba y disfrutaba del sol, mientras que una hormiga trabajaba sin descanso recolectando comida. La cigarra se burló de la hormiga por no divertirse.', 
	'https://lh3.googleusercontent.com/d/1v4KYKzWp3V9kIe66zrxJzgssGxuNloqW=w500-h500', 
	'Pasó el tiempo y llegó el invierno. La cigarra, sin comida, pidió ayuda a la hormiga, pero esta le recordó que mientras ella trabajaba, la cigarra se divertía. La cigarra aprendió la importancia del esfuerzo.', 
	NULL, '¿Qué hacía la cigarra durante el verano?', 
	'Cantaba y disfrutaba del sol', 'Trabajaba recolectando comida', 'Dormía todo el día', 'Ayudaba a la hormiga', 'A', 1, 1),
('COMPRENSIÓN LECTORA', '104', 'La cigarra y la hormiga', 
	NULL, 'https://lh3.googleusercontent.com/d/1v4KYKzWp3V9kIe66zrxJzgssGxuNloqW=w500-h500', 
	NULL, NULL, '¿Por qué la hormiga trabajaba tanto en verano?', 
	'Porque le gustaba trabajar', 'Porque tenía que almacenar comida', 'Porque no tenía amigos', 'Porque quería impresionar a la cigarra', 'B', 1, 1),
('COMPRENSIÓN LECTORA', '104', 'La cigarra y la hormiga', 
	NULL, 'https://lh3.googleusercontent.com/d/1v4KYKzWp3V9kIe66zrxJzgssGxuNloqW=w500-h500', 
	NULL, NULL, '¿Qué le pidió la cigarra a la hormiga cuando llegó el invierno?', 
	'Que la dejara cantar con ella', 'Que la ayudara a construir una casa', 'Que le diera comida', 'Que la dejara dormir en su hormiguero', 'C', 1, 1),
('COMPRENSIÓN LECTORA', '104', 'La cigarra y la hormiga', 
	NULL, 'https://lh3.googleusercontent.com/d/1v4KYKzWp3V9kIe66zrxJzgssGxuNloqW=w500-h500', 
	NULL, NULL, '¿Qué le respondió la hormiga a la cigarra?', 
	'“No tengo suficiente comida para compartir”', '“Puedes quedarte conmigo”', '“Cantaré contigo para ayudarte”', '“Eres mi amiga, te ayudaré”', 'A', 1, 1),
('COMPRENSIÓN LECTORA', '104', 'La cigarra y la hormiga', 
	NULL, 'https://lh3.googleusercontent.com/d/1v4KYKzWp3V9kIe66zrxJzgssGxuNloqW=w500-h500', 
	NULL, NULL, '¿Cuál es la enseñanza de la fábula?', 
	'Solo los insectos trabajan', 'Es importante esforzarse y prepararse', 'La cigarra era más sabia que la hormiga', 'No hay que cantar en el verano', 'B', 1, 1),

('COMPRENSIÓN LECTORA', '105', 'El patito feo', 'Un día, en un granja, nació un patito diferente a los demás. Era más grande y de color gris. Todos los animales lo rechazaban y se burlaban de él.', 
 'https://lh3.googleusercontent.com/d/1NhoQANghtdwvkXas4mH55ohhGaRclbsJ=w500-h500', 
 'Pasó el tiempo y el patito creció. Un día vio su reflejo en el agua y se dio cuenta de que no era un pato feo, sino un hermoso cisne.', 
 NULL, '¿Por qué los demás animales rechazaban al patito?', 
 'Porque era muy pequeño', 'Porque no podía nadar', 'Porque tenía un color diferente', 'Porque no tenía familia', 
 'C', 1, 1),
('COMPRENSIÓN LECTORA', '105', 'El patito feo', NULL, 
 'https://lh3.googleusercontent.com/d/1NhoQANghtdwvkXas4mH55ohhGaRclbsJ=w500-h500', 
 NULL, NULL, '¿Qué hizo el patito cuando se sintió rechazado?', 
 'Se escondió y lloró', 'Peleó con los demás animales', 'Decidió buscar otro lugar', 'No hizo nada', 
 'C', 1, 1),
('COMPRENSIÓN LECTORA', '105', 'El patito feo', NULL, 
 'https://lh3.googleusercontent.com/d/1NhoQANghtdwvkXas4mH55ohhGaRclbsJ=w500-h500', 
 NULL, NULL, '¿Qué descubrió el patito al final de la historia?', 
 'Que en realidad era un cisne', 'Que los patos no pueden volar', 'Que todos los animales son iguales', 'Que debía cambiar su color', 
 'A', 1, 1),
('COMPRENSIÓN LECTORA', '105', 'El patito feo', NULL, 
 'https://lh3.googleusercontent.com/d/1NhoQANghtdwvkXas4mH55ohhGaRclbsJ=w500-h500', 
 NULL, NULL, '¿Cómo se sintió el patito cuando vio su reflejo en el agua?', 
 'Triste', 'Feliz y sorprendido', 'Enfadado', 'Igual que antes', 
 'B', 1, 1),
('COMPRENSIÓN LECTORA', '105', 'El patito feo', NULL, 
 'https://lh3.googleusercontent.com/d/1NhoQANghtdwvkXas4mH55ohhGaRclbsJ=w500-h500', 
 NULL, NULL, '¿Cuál es la enseñanza de esta historia?', 
 'No hay que confiar en los demás', 'La belleza está en el interior', 'Hay que ser iguales a los demás', 'Es mejor estar solo', 
 'B', 1, 1),

('COMPRENSIÓN LECTORA', '106', 'Caperucita Roja', 'Una niña llamada Caperucita Roja iba a visitar a su abuela en el bosque. Su madre le advirtió que no hablara con extraños.', 'https://lh3.googleusercontent.com/d/1TBq07KACKFcSCwb6exXjLIkVT2yiHe9O=w500-h500', 'En el camino, Caperucita se encontró con un lobo que la engañó y llegó primero a casa de la abuela. El lobo se disfrazó de la abuela para engañarla. Un cazador que pasaba por el lugar las salvó.', NULL, '¿A quién iba a visitar Caperucita Roja?', 'A su tía', 'A su madre', 'A su abuela', 'A su hermana', 'C', 1, 1),
('COMPRENSIÓN LECTORA', '106', 'Caperucita Roja', NULL, 'https://lh3.googleusercontent.com/d/1TBq07KACKFcSCwb6exXjLIkVT2yiHe9O=w500-h500', NULL, NULL, '¿Qué consejo le dio su madre antes de salir?', 'Que no hablara con extraños', 'Que no corriera', 'Que no tomara atajos', 'Que no llevara la capa roja', 'A', 1, 1),
('COMPRENSIÓN LECTORA', '106', 'Caperucita Roja', NULL, 'https://lh3.googleusercontent.com/d/1TBq07KACKFcSCwb6exXjLIkVT2yiHe9O=w500-h500', NULL, NULL, '¿Cómo engañó el lobo a Caperucita?', 'Se escondió en el bosque', 'Se disfrazó de su madre', 'Se disfrazó de la abuela', 'Le dio un regalo', 'C', 1, 1),
('COMPRENSIÓN LECTORA', '106', 'Caperucita Roja', NULL, 'https://lh3.googleusercontent.com/d/1TBq07KACKFcSCwb6exXjLIkVT2yiHe9O=w500-h500', NULL, NULL, '¿Quién salvó a Caperucita y a su abuela?', 'Un cazador', 'Su madre', 'Un oso', 'Un lobo bueno', 'A', 1, 1),
('COMPRENSIÓN LECTORA', '106', 'Caperucita Roja', NULL, 'https://lh3.googleusercontent.com/d/1TBq07KACKFcSCwb6exXjLIkVT2yiHe9O=w500-h500', NULL, NULL, '¿Qué enseñanza deja esta historia?', 'No hay que visitar a los abuelos', 'No hay que hablar con extraños', 'Hay que confiar en todos', 'Es bueno tomar atajos', 'B', 1, 1),

    ('COMPRENSIÓN LECTORA', 107, 'La zorra y las uvas', 'Una zorra caminaba por el bosque cuando vio un racimo de uvas colgando de una vid muy alta. Eran grandes, moradas y parecían deliciosas. La zorra saltó una y otra vez para alcanzarlas, pero no pudo.', 'https://lh3.googleusercontent.com/d/1rvKmkc6lqKkGKMG8DptqGCUwJlGj77Qg=w500-h500', 'Cansada de intentarlo, la zorra se alejó diciendo: "¡Bah! Seguro que están verdes y no me gustarían". Así, la zorra se fue sin probarlas, tratando de convencerse de que no le importaban.', NULL, '¿Qué vio la zorra en el árbol?', 'Manzanas', 'Uvas', 'Naranjas', 'Peras', 'B', 1, 1),
    ('COMPRENSIÓN LECTORA', 107, 'La zorra y las uvas', NULL, 'https://lh3.googleusercontent.com/d/1rvKmkc6lqKkGKMG8DptqGCUwJlGj77Qg=w500-h500', NULL, NULL, '¿Por qué la zorra no pudo comer las uvas?', 'Porque estaban en el suelo', 'Porque estaban muy altas', 'Porque estaban podridas', 'Porque alguien más las tomó', 'B', 1, 1),
    ('COMPRENSIÓN LECTORA', 107, 'La zorra y las uvas', NULL, 'https://lh3.googleusercontent.com/d/1rvKmkc6lqKkGKMG8DptqGCUwJlGj77Qg=w500-h500', NULL, NULL, '¿Cómo se sintió la zorra cuando no pudo alcanzar las uvas?', 'Alegre', 'Triste', 'Enfadada', 'Cansada y frustrada', 'D', 1, 1),
    ('COMPRENSIÓN LECTORA', 107, 'La zorra y las uvas', NULL, 'https://lh3.googleusercontent.com/d/1rvKmkc6lqKkGKMG8DptqGCUwJlGj77Qg=w500-h500', NULL, NULL, '¿Qué dijo la zorra al final?', 'Que las uvas estaban verdes y no le gustaban', 'Que intentaría de nuevo mañana', 'Que pediría ayuda', 'Que buscaría otro racimo', 'A', 1, 1),
    ('COMPRENSIÓN LECTORA', 107, 'La zorra y las uvas', NULL, 'https://lh3.googleusercontent.com/d/1rvKmkc6lqKkGKMG8DptqGCUwJlGj77Qg=w500-h500', NULL, NULL, '¿Cuál es la enseñanza de esta fábula?', 'Que siempre debemos compartir con los demás', 'Que no debemos rendirnos fácilmente', 'Que es mejor decir la verdad y aceptar cuando algo no se puede conseguir', 'Que las uvas son la mejor fruta', 'C', 1, 1),

('COMPRENSIÓN LECTORA', '108', 'Pedro y el lobo', 'Pedro era un niño que cuidaba ovejas en el campo. Un día, decidió hacer una broma y gritó “¡Lobo! ¡Lobo!” para asustar a los aldeanos.', 'https://lh3.googleusercontent.com/d/1O_doLx3Vrv9CwnTjCJx_frXo60E-k3q-=w500-h500', 'Los aldeanos corrieron a ayudarlo, pero descubrieron que era mentira. Cuando el lobo apareció de verdad, nadie le creyó y no lo ayudaron.', NULL, '¿Qué hacía Pedro en el campo?', 'Cuidaba caballos', 'Jugaba con otros niños', 'Cuidaba ovejas', 'Cazaba lobos', 'C', 1, 1),
('COMPRENSIÓN LECTORA', '108', 'Pedro y el lobo', NULL, 'https://lh3.googleusercontent.com/d/1O_doLx3Vrv9CwnTjCJx_frXo60E-k3q-=w500-h500', NULL, NULL, '¿Por qué Pedro gritó “¡Lobo!” la primera vez?', 'Como una broma', 'Para pedir ayuda de verdad', 'Porque el lobo estaba atacando', 'Para entretener a las ovejas', 'A', 1, 1),
('COMPRENSIÓN LECTORA', '108', 'Pedro y el lobo', NULL, 'https://lh3.googleusercontent.com/d/1O_doLx3Vrv9CwnTjCJx_frXo60E-k3q-=w500-h500', NULL, NULL, '¿Cómo reaccionaron los aldeanos la primera vez?', 'No hicieron nada', 'Corrieron a ayudarlo', 'Se enojaron con él', 'Buscaron al lobo', 'B', 1, 1),
('COMPRENSIÓN LECTORA', '108', 'Pedro y el lobo', NULL, 'https://lh3.googleusercontent.com/d/1O_doLx3Vrv9CwnTjCJx_frXo60E-k3q-=w500-h500', NULL, NULL, '¿Qué pasó cuando el lobo apareció de verdad?', 'Pedro lo atrapó', 'Los aldeanos lo ayudaron', 'Nadie le creyó', 'El lobo se escapó', 'C', 1, 1),
('COMPRENSIÓN LECTORA', '108', 'Pedro y el lobo', NULL, 'https://lh3.googleusercontent.com/d/1O_doLx3Vrv9CwnTjCJx_frXo60E-k3q-=w500-h500', NULL, NULL, '¿Cuál es la enseñanza de la historia?', 'Es divertido engañar a los demás', 'Hay que decir siempre la verdad', 'Los lobos siempre mienten', 'No hay que cuidar ovejas', 'B', 1, 1),

	('COMPRENSIÓN LECTORA', 109, 'El gigante egoísta', 'Un gigante tenía un hermoso jardín, pero no dejaba que los niños jugaran en él. Construyó un muro alto para que nadie entrara.', 'https://lh3.googleusercontent.com/d/1mfLmrlb4E3tXrJvdJ7fgXXrXVTTW6moc=w500-h500', 'Sin los niños, el jardín se volvió frío y triste. Un día, un niño pequeño logró entrar y el gigante se dio cuenta de su error. Derribó el muro y dejó que los niños jugaran, haciendo que la primavera volviera.', NULL, '¿Por qué el gigante construyó un muro?', 'Porque quería proteger a los niños', 'Porque no quería compartir su jardín', 'Porque le gustaban los muros', 'Porque el jardín estaba en mal estado', 'B', 1, 1),
	('COMPRENSIÓN LECTORA', 109, 'El gigante egoísta', NULL, 'https://lh3.googleusercontent.com/d/1mfLmrlb4E3tXrJvdJ7fgXXrXVTTW6moc=w500-h500', NULL, NULL, '¿Qué pasó con el jardín cuando el gigante prohibió la entrada a los niños?', 'Se volvió más hermoso', 'Se llenó de animales', 'Se volvió frío y triste', 'Crecieron más flores', 'C', 1, 1),
	('COMPRENSIÓN LECTORA', 109, 'El gigante egoísta', NULL, 'https://lh3.googleusercontent.com/d/1mfLmrlb4E3tXrJvdJ7fgXXrXVTTW6moc=w500-h500', NULL, NULL, '¿Qué hizo el gigante cuando vio a un niño dentro de su jardín?', 'Se enojó y lo echó', 'Construyó otro muro', 'Le regaló flores', 'Se dio cuenta de su error', 'D', 1, 1),
	('COMPRENSIÓN LECTORA', 109, 'El gigante egoísta', NULL, 'https://lh3.googleusercontent.com/d/1mfLmrlb4E3tXrJvdJ7fgXXrXVTTW6moc=w500-h500', NULL, NULL, '¿Cómo cambió el jardín cuando el gigante dejó entrar a los niños?', 'Siguió igual', 'Se volvió más frío', 'Desaparecieron los árboles', 'Se llenó de flores y volvió la primavera', 'D', 1, 1),
	('COMPRENSIÓN LECTORA', 109, 'El gigante egoísta', NULL, 'https://lh3.googleusercontent.com/d/1mfLmrlb4E3tXrJvdJ7fgXXrXVTTW6moc=w500-h500', NULL, NULL, '¿Cuál es la enseñanza de esta historia?', 'Es mejor estar solo', 'Hay que compartir para ser felices', 'Los gigantes son malos', 'Los jardines no deben tener muros', 'B', 1, 1),

('COMPRENSIÓN LECTORA', '110', 'El traje nuevo del emperador', 'Un emperador vanidoso quería tener la mejor ropa del reino. Dos sastres lo engañaron diciéndole que harían un traje invisible para los tontos.', 'https://lh3.googleusercontent.com/d/1NK3SSvg6nE8BZUh9R1QXCoryzVXlzUzX=w500-h500', 'Todos fingieron ver el traje para no parecer tontos. Pero un niño dijo la verdad: el emperador estaba desnudo.', NULL, '¿Qué prometieron los sastres al emperador?', 'Un traje invisible para los tontos', 'Un traje mágico', 'Un traje de oro', 'Un traje común', 'A', 1, 1),
('COMPRENSIÓN LECTORA', '110', 'El traje nuevo del emperador', NULL, 'https://lh3.googleusercontent.com/d/1NK3SSvg6nE8BZUh9R1QXCoryzVXlzUzX=w500-h501', NULL, NULL, '¿Por qué todos fingieron ver el traje?', 'Porque era muy bonito', 'Porque era realmente invisible', 'Porque les gustaba', 'Porque no querían parecer tontos', 'D', 1, 1),
('COMPRENSIÓN LECTORA', '110', 'El traje nuevo del emperador', NULL, 'https://lh3.googleusercontent.com/d/1NK3SSvg6nE8BZUh9R1QXCoryzVXlzUzX=w500-h502', NULL, NULL, '¿Quién dijo la verdad sobre el traje?', 'Un niño', 'Un anciano', 'Otro emperador', 'Un sastre', 'A', 1, 1),
('COMPRENSIÓN LECTORA', '110', 'El traje nuevo del emperador', NULL, 'https://lh3.googleusercontent.com/d/1NK3SSvg6nE8BZUh9R1QXCoryzVXlzUzX=w500-h503', NULL, NULL, '¿Cómo reaccionó el emperador al escuchar la verdad?', 'Se rió', 'Se enojó', 'Se dio cuenta de su error, pero siguió caminando', 'Se puso otro traje', 'C', 1, 1),
('COMPRENSIÓN LECTORA', '110', 'El traje nuevo del emperador', NULL, 'https://lh3.googleusercontent.com/d/1NK3SSvg6nE8BZUh9R1QXCoryzVXlzUzX=w500-h504', NULL, NULL, '¿Qué enseñanza nos deja esta historia?', 'Es importante tener la mejor ropa', 'Hay que decir siempre la verdad', 'No hay que confiar en los sastres', 'Es mejor guardar silencio', 'B', 1, 1),

('COMPRENSIÓN LECTORA', '111', 'Un día en la escuela', 
 'Hoy es un día especial en la escuela. Los niños llegan temprano y la maestra los saluda con una gran sonrisa. Hoy aprenderán algo nuevo y jugarán con sus amigos.',
 'https://lh3.googleusercontent.com/d/1ZNmc3kmi92AUp-ifLWYpo4J1OB_ytdCA=w500-h500',
 'Después de la clase, los niños salen al recreo. Juegan en el patio y comparten su merienda. Luego, regresan al aula para seguir aprendiendo.',
 NULL, '¿Cómo reciben los niños a la maestra?', 'Con tristeza', 'Con una gran sonrisa', 'Con enojo', 'Con miedo', 'B', 1, 1),
('COMPRENSIÓN LECTORA', '111', 'Un día en la escuela', 
 NULL, 'https://lh3.googleusercontent.com/d/1ZNmc3kmi92AUp-ifLWYpo4J1OB_ytdCA=w500-h500', 
 NULL, NULL, '¿Qué hacen los niños después de la clase?', 'Se van a casa', 'Salen al recreo', 'Se quedan dormidos', 'Ven televisión', 'B', 1, 1),
('COMPRENSIÓN LECTORA', '111', 'Un día en la escuela', 
 NULL, 'https://lh3.googleusercontent.com/d/1ZNmc3kmi92AUp-ifLWYpo4J1OB_ytdCA=w500-h500', 
 NULL, NULL, '¿Cómo se sienten los niños en la escuela?', 'Felices y emocionados', 'Aburridos', 'Tristes', 'Enojados', 'A', 1, 1),
('COMPRENSIÓN LECTORA', '111', 'Un día en la escuela', 
 NULL, 'https://lh3.googleusercontent.com/d/1ZNmc3kmi92AUp-ifLWYpo4J1OB_ytdCA=w500-h500', 
 NULL, NULL, '¿Dónde juegan los niños en el recreo?', 'En el aula', 'En sus casas', 'En la biblioteca', 'En el patio', 'D', 1, 1),
('COMPRENSIÓN LECTORA', '111', 'Un día en la escuela', 
 NULL, 'https://lh3.googleusercontent.com/d/1ZNmc3kmi92AUp-ifLWYpo4J1OB_ytdCA=w500-h500', 
 NULL, NULL, '¿Por qué es importante la escuela?', 'Porque es un lugar donde aprendemos y hacemos amigos', 'Porque es un lugar aburrido', 'Porque no podemos jugar', 'Porque no nos gusta', 'A', 1, 1),

('COMPRENSIÓN LECTORA', '112', 'Un paseo en familia', 
 'Hoy es un día soleado y la familia de Juan decide salir de paseo. Van al parque con una canasta de comida para hacer un picnic.', 
 'https://lh3.googleusercontent.com/d/1erEFEA78P8fEFMY4-2Osy6FIiwtufitM=w500-h500', 
 'En el parque, juegan, corren y disfrutan de la naturaleza. Juan está muy feliz porque puede compartir con su familia.', 
 NULL, '¿A dónde va la familia de Juan?', 'A la escuela', 'Al parque', 'Al supermercado', 'A la playa', 'B', 1, 1),
('COMPRENSIÓN LECTORA', '112', 'Un paseo en familia', 
 NULL, 'https://lh3.googleusercontent.com/d/1erEFEA78P8fEFMY4-2Osy6FIiwtufitM=w500-h500', NULL, 
 NULL, '¿Qué llevan para el paseo?', 'Libros', 'Juguetes', 'Nada', 'Una canasta con comida', 'D', 1, 1),
('COMPRENSIÓN LECTORA', '112', 'Un paseo en familia', 
 NULL, 'https://lh3.googleusercontent.com/d/1erEFEA78P8fEFMY4-2Osy6FIiwtufitM=w500-h500', NULL, 
 NULL, '¿Qué hacen en el parque?', 'Juegan, corren y disfrutan de la naturaleza', 'Ven televisión', 'Duermen', 'Estudian', 'A', 1, 1),
('COMPRENSIÓN LECTORA', '112', 'Un paseo en familia', 
 NULL, 'https://lh3.googleusercontent.com/d/1erEFEA78P8fEFMY4-2Osy6FIiwtufitM=w500-h500', NULL, 
 NULL, '¿Por qué Juan está feliz?', 'Porque está en casa', 'Porque está con su familia', 'Porque está solo', 'Porque ganó un premio', 'B', 1, 1),
('COMPRENSIÓN LECTORA', '112', 'Un paseo en familia', 
 NULL, 'https://lh3.googleusercontent.com/d/1erEFEA78P8fEFMY4-2Osy6FIiwtufitM=w500-h500', NULL, 
 NULL, '¿Cuál es el mensaje de la historia?', 'Es divertido compartir en familia', 'Es mejor estar solo', 'No hay que salir al parque', 'La familia no es importante', 'A', 1, 1);