--INSERT CURSO INGLÉS

INSERT INTO competencia(
	"NOMBRE_COMPETENCIA", "PESO_COMPETENCIA", "DESCRIPCION", "FECHA_DISPONIBILIDAD", "FECHA_INICIO", "FECHA_FIN", "HORA_INICIO", "ORDEN_COMPETENCIA", "ESTADO_COMPETENCIA", "DEPENDENCIA_COMPETENCIA", "ID_ETAPA", "ID_PROCESO", "URL_IMAGEN")
	VALUES ('INGLÉS', 33.33, 'Evaluación de Inglés', '2025-01-01', '2025-01-01', '2025-12-31', '16:00:00', 4, 'Pendiente', null, 2, 1, 'https://res.cloudinary.com/djp7gmsgk/image/upload/v1741130365/examen-ingles_q31pj0.jpg');



--INSERT CRITERIO EVALUACION PARA INGLÉS
INSERT INTO criterio_evaluacion(
	"ID_COMPETENCIA", "PUNTUACION_MAXIMA", "PESO", "NUMERO_PREGUNTAS", "PUNTAJE_POR_PREGUNTA", "PUNTAJE_MAXIMO", "PUNTAJE_MINIMO_APROBATORIO", "TIEMPO_POR_PREGUNTA", "TIEMPO_LIMITE")
	VALUES (4, 100.00, 33.33, 20, 5.00, 100.00, 60.00, 2.00, '00:05:00');



--INSERT DE PREGUNTAS PARA INGLÉS
INSERT INTO pregunta(
    "TIPO_EVALUACION", "GRUPO", "TEXTO_TITULO", "TEXTO_SUPERIOR", "TEXTO_IMAGEN", "TEXTO_INFERIOR", "ID_ARCHIVO_CARGA", "PREGUNTA", "OPCION_A", "OPCION_B", "OPCION_C", "OPCION_D", "RESPUESTA_CORRECTA", "ID_COMPETENCIA", "ID_GRADO")
VALUES
('INGLÉS', NULL, 'Colors / Colores', 'What color is the sky? / ¿De qué color es el cielo?', 'https://res.cloudinary.com/djp7gmsgk/image/upload/v1741133175/cielo-azul_zhaybl.jpg', NULL, NULL, 'Select the correct color / Selecciona el color correcto', 'Red / Rojo', 'Green / Verde', 'Blue / Azul', 'Yellow / Amarillo', 'C', 4, 1),
('INGLÉS', NULL, 'Animals / Animales', 'Which animal says "meow"? / ¿Qué animal dice "miau"?', 'https://res.cloudinary.com/djp7gmsgk/image/upload/v1741134110/animales_l8af3z.jpg', NULL, NULL, 'Choose the correct animal / Elige el animal correcto', 'Dog / Perro', 'Cat / Gato', 'Cow / Vaca', 'Horse / Caballo', 'B', 4, 1),
('INGLÉS', NULL, 'Numbers / Números', 'What number comes after five? / ¿Qué número viene después del cinco?', 'https://res.cloudinary.com/djp7gmsgk/image/upload/v1741134776/numeros_pvdmrk.jpg', NULL, NULL, 'Select the correct number / Selecciona el número correcto', 'Three / Tres', 'Four / Cuatro', 'Six / Seis', 'Seven / Siete', 'C', 4, 1),
('INGLÉS', NULL, 'Fruits / Frutas', 'Which fruit is yellow? / ¿Qué fruta es amarilla?', 'https://res.cloudinary.com/djp7gmsgk/image/upload/v1741135090/frutas_v1sras.jpg', NULL, NULL, 'Pick the correct fruit / Elige la fruta correcta', 'Apple / Manzana', 'Banana / Plátano', 'Grapes / Uvas', 'Orange / Naranja', 'B', 4, 1),
('INGLÉS', NULL, 'Days of the week / Días de la semana', 'What day comes after Monday? / ¿Qué día viene después del lunes?', NULL, NULL, NULL, 'Choose the next day / Elige el siguiente día', 'Tuesday / Martes', 'Thursday / Jueves', 'Friday / Viernes', 'Sunday / Domingo', 'A', 4, 1),
('INGLÉS', NULL, 'Weather / Clima', 'What do we use when it rains? / ¿Qué usamos cuando llueve?', NULL, NULL, NULL, 'Select the correct item / Selecciona el objeto correcto', 'Hat / Sombrero', 'Umbrella / Paraguas', 'Sunglasses / Gafas de sol', 'Scarf / Bufanda', 'B', 4, 1),
('INGLÉS', NULL, 'Shapes / Figuras', 'Which shape has three sides? / ¿Qué figura tiene tres lados?', NULL, NULL, NULL, 'Pick the correct shape / Elige la figura correcta', 'Square / Cuadrado', 'Circle / Círculo', 'Triangle / Triángulo', 'Rectangle / Rectángulo', 'C', 4, 1),
('INGLÉS', NULL, 'Body parts / Partes del cuerpo', 'What do we use to see? / ¿Qué usamos para ver?', NULL, NULL, NULL, 'Select the correct body part / Selecciona la parte del cuerpo correcta', 'Nose / Nariz', 'Mouth / Boca', 'Eyes / Ojos', 'Ears / Oídos', 'C', 4, 1),
('INGLÉS', NULL, 'Actions / Acciones', 'What do we do with our ears? / ¿Qué hacemos con nuestros oídos?', NULL, NULL, NULL, 'Choose the right action / Elige la acción correcta', 'See / Ver', 'Hear / Escuchar', 'Run / Correr', 'Jump / Saltar', 'B', 4, 1),
('INGLÉS', NULL, 'Food / Comida', 'Which one is a vegetable? / ¿Cuál es un vegetal?', NULL, NULL, NULL, 'Choose the correct answer / Elige la respuesta correcta', 'Apple / Manzana', 'Carrot / Zanahoria', 'Cake / Pastel', 'Milk / Leche', 'B', 4, 1),
('INGLÉS', NULL, 'Clothes / Ropa', 'What do we wear on our feet? / ¿Qué usamos en los pies?', NULL, NULL, NULL, 'Select the correct clothing item / Selecciona la prenda correcta', 'Hat / Sombrero', 'Shirt / Camisa', 'Shoes / Zapatos', 'Gloves / Guantes', 'C', 4, 1),
('INGLÉS', NULL, 'Seasons / Estaciones', 'Which season is the coldest? / ¿Cuál es la estación más fría?', NULL, NULL, NULL, 'Pick the correct season / Elige la estación correcta', 'Summer / Verano', 'Winter / Invierno', 'Spring / Primavera', 'Autumn / Otoño', 'B', 4, 1),
('INGLÉS', NULL, 'Feelings / Sentimientos', 'What do you say when you meet someone new? / ¿Qué dices cuando conoces a alguien nuevo?', NULL, NULL, NULL, 'Choose the correct greeting / Elige el saludo correcto', 'Goodbye / Adiós', 'Thank you / Gracias', 'Hello / Hola', 'Sorry / Lo siento', 'C', 4, 1),
('INGLÉS', NULL, 'Transport / Transporte', 'Which one can fly? / ¿Cuál puede volar?', NULL, NULL, NULL, 'Select the correct answer / Selecciona la respuesta correcta', 'Car / Carro', 'Bicycle / Bicicleta', 'Airplane / Avión', 'Train / Tren', 'C', 4, 1),
('INGLÉS', NULL, 'Household items / Objetos del hogar', 'Where do we sleep? / ¿Dónde dormimos?', NULL, NULL, NULL, 'Pick the correct answer / Elige la respuesta correcta', 'Chair / Silla', 'Bed / Cama', 'Table / Mesa', 'Sofa / Sofá', 'B', 4, 1),
('INGLÉS', NULL, 'Opposites / Opuestos', 'What is the opposite of "big"? / ¿Cuál es el opuesto de "grande"?', NULL, NULL, NULL, 'Choose the correct opposite / Elige el opuesto correcto', 'Small / Pequeño', 'Fast / Rápido', 'Tall / Alto', 'Short / Corto', 'A', 4, 1),
('INGLÉS', NULL, 'School objects / Objetos de la escuela', 'What do we use to write? / ¿Qué usamos para escribir?', NULL, NULL, NULL, 'Select the correct item / Selecciona el objeto correcto', 'Scissors / Tijeras', 'Pencil / Lápiz', 'Eraser / Borrador', 'Ruler / Regla', 'B', 4, 1),
('INGLÉS', NULL, 'Actions / Acciones', 'What do we do with our legs? / ¿Qué hacemos con nuestras piernas?', NULL, NULL, NULL, 'Pick the correct action / Elige la acción correcta', 'Write / Escribir', 'Eat / Comer', 'Run / Correr', 'Clap / Aplaudir', 'C', 4, 1),
('INGLÉS', NULL, 'Nature / Naturaleza', 'Which one grows on a tree? / ¿Cuál crece en un árbol?', NULL, NULL, NULL, 'Choose the correct answer / Elige la respuesta correcta', 'Rock / Roca', 'Fish / Pez', 'Bird / Pájaro', 'Apple / Manzana', 'D', 4, 1),
('INGLÉS', NULL, 'Professions / Profesiones', 'Who teaches at school? / ¿Quién enseña en la escuela?', NULL, NULL, NULL, 'Select the correct profession / Selecciona la profesión correcta', 'Doctor / Doctor', 'Firefighter / Bombero', 'Teacher / Maestro', 'Police officer / Policía', 'C', 4, 1),
('INGLÉS', NULL, 'Colors / Colores', 'Which one is the color of the sun? / ¿Cuál es el color del sol?', NULL, NULL, NULL, 'Choose the correct color / Elige el color correcto', 'Blue / Azul', 'Yellow / Amarillo', 'Green / Verde', 'Red / Rojo', 'B', 4, 1),
('INGLÉS', NULL, 'Animals / Animales', 'Which animal says "meow"? / ¿Qué animal dice "miau"?', NULL, NULL, NULL, 'Pick the correct animal / Elige el animal correcto', 'Dog / Perro', 'Cat / Gato', 'Cow / Vaca', 'Horse / Caballo', 'B', 4, 1),
('INGLÉS', NULL, 'Numbers / Números', 'What comes after 5? / ¿Qué número viene después del 5?', NULL, NULL, NULL, 'Select the correct number / Selecciona el número correcto', '4', '5', '6', '7', 'C', 4, 1),
('INGLÉS', NULL, 'Fruits / Frutas', 'Which fruit is red and round? / ¿Cuál fruta es roja y redonda?', NULL, NULL, NULL, 'Choose the correct fruit / Elige la fruta correcta', 'Banana / Plátano', 'Grapes / Uvas', 'Apple / Manzana', 'Orange / Naranja', 'C', 4, 1),
('INGLÉS', NULL, 'Body parts / Partes del cuerpo', 'What do we use to see? / ¿Qué usamos para ver?', NULL, NULL, NULL, 'Pick the correct body part / Elige la parte del cuerpo correcta', 'Nose / Nariz', 'Mouth / Boca', 'Eyes / Ojos', 'Hands / Manos', 'C', 4, 1),
('INGLÉS', NULL, 'Weather / Clima', 'What do we use when it rains? / ¿Qué usamos cuando llueve?', NULL, NULL, NULL, 'Select the correct item / Selecciona el objeto correcto', 'Hat / Sombrero', 'Sunglasses / Gafas de sol', 'Umbrella / Paraguas', 'Scarf / Bufanda', 'C', 4, 1),
('INGLÉS', NULL, 'Shapes / Figuras', 'Which shape has four equal sides? / ¿Qué figura tiene cuatro lados iguales?', NULL, NULL, NULL, 'Choose the correct shape / Elige la figura correcta', 'Circle / Círculo', 'Triangle / Triángulo', 'Square / Cuadrado', 'Rectangle / Rectángulo', 'C', 4, 1),
('INGLÉS', NULL, 'Daily routines / Rutinas diarias', 'What do we do in the morning? / ¿Qué hacemos en la mañana?', NULL, NULL, NULL, 'Pick the correct action / Elige la acción correcta', 'Sleep / Dormir', 'Brush teeth / Cepillarse los dientes', 'Watch TV / Ver televisión', 'Read a book / Leer un libro', 'B', 4, 1),
('INGLÉS', NULL, 'Toys / Juguetes', 'Which one is a toy? / ¿Cuál es un juguete?', NULL, NULL, NULL, 'Select the correct toy / Selecciona el juguete correcto', 'Ball / Pelota', 'Chair / Silla', 'Clock / Reloj', 'Pencil / Lápiz', 'A', 4, 1),
('INGLÉS', NULL, 'Actions / Acciones', 'What do we do with a book? / ¿Qué hacemos con un libro?', NULL, NULL, NULL, 'Pick the correct action / Elige la acción correcta', 'Read / Leer', 'Eat / Comer', 'Throw / Lanzar', 'Kick / Patear', 'A', 4, 1),
('INGLÉS', NULL, 'Family / Familia', 'Who is your father’s mother? / ¿Quién es la madre de tu padre?', NULL, NULL, NULL, 'Choose the correct family member / Elige el miembro de la familia correcto', 'Aunt / Tía', 'Sister / Hermana', 'Grandmother / Abuela', 'Cousin / Primo', 'C', 4, 1),
('INGLÉS', NULL, 'Months / Meses', 'Which is the first month of the year? / ¿Cuál es el primer mes del año?', NULL, NULL, NULL, 'Select the correct month / Selecciona el mes correcto', 'December / Diciembre', 'March / Marzo', 'January / Enero', 'July / Julio', 'C', 4, 1),
('INGLÉS', NULL, 'Time / Tiempo', 'How many hours are in a day? / ¿Cuántas horas tiene un día?', NULL, NULL, NULL, 'Pick the correct number / Elige el número correcto', '12', '24', '30', '60', 'B', 4, 1),
('INGLÉS', NULL, 'Musical instruments / Instrumentos musicales', 'Which one is a musical instrument? / ¿Cuál es un instrumento musical?', NULL, NULL, NULL, 'Choose the correct instrument / Elige el instrumento correcto', 'Guitar / Guitarra', 'Spoon / Cuchara', 'Chair / Silla', 'Socks / Calcetines', 'A', 4, 1),
('INGLÉS', NULL, 'Occupations / Ocupaciones', 'Who takes care of sick people? / ¿Quién cuida a las personas enfermas?', NULL, NULL, NULL, 'Select the correct profession / Selecciona la profesión correcta', 'Chef / Cocinero', 'Doctor / Doctor', 'Teacher / Maestro', 'Police officer / Policía', 'B', 4, 1),
('INGLÉS', NULL, 'Directions / Direcciones', 'What is the opposite of "left"? / ¿Cuál es el opuesto de "izquierda"?', NULL, NULL, NULL, 'Pick the correct direction / Elige la dirección correcta', 'Up / Arriba', 'Down / Abajo', 'Right / Derecha', 'Back / Atrás', 'C', 4, 1),
('INGLÉS', NULL, 'Days of the week / Días de la semana', 'Which day comes after Monday? / ¿Qué día viene después del lunes?', NULL, NULL, NULL, 'Choose the correct day / Elige el día correcto', 'Tuesday / Martes', 'Thursday / Jueves', 'Friday / Viernes', 'Sunday / Domingo', 'A', 4, 1),
('INGLÉS', NULL, 'Healthy food / Comida saludable', 'Which one is a healthy snack? / ¿Cuál es un bocadillo saludable?', NULL, NULL, NULL, 'Select the correct food / Selecciona la comida correcta', 'Candy / Dulces', 'Chips / Papas fritas', 'Carrots / Zanahorias', 'Soda / Gaseosa', 'C', 4, 1),
('INGLÉS', NULL, 'Modes of transport / Medios de transporte', 'Which one moves on water? / ¿Cuál se mueve en el agua?', NULL, NULL, NULL, 'Choose the correct transport / Elige el transporte correcto', 'Car / Coche', 'Bicycle / Bicicleta', 'Boat / Barco', 'Train / Tren', 'C', 4, 1),
('INGLÉS', NULL, 'Rooms of the house / Habitaciones de la casa', 'Where do we cook food? / ¿Dónde cocinamos la comida?', NULL, NULL, NULL, 'Pick the correct room / Elige la habitación correcta', 'Bathroom / Baño', 'Kitchen / Cocina', 'Bedroom / Dormitorio', 'Garage / Garaje', 'B', 4, 1);